// "Best X for Y" AEO listicles — ranked destination guides that answer real search/voice queries
// (best islands for snorkeling, family beaches, cool-season mountains, honeymoon escapes, nightlife,
// rainy-season trips). Each item links to a REAL city hub + its where-to-stay guide — nothing
// fabricated, all destinations already covered on the site. Writes articles{,-en}; surfaced on the
// destinations hub (gen-hubs BESTOF) + search index. Run: node _internal/gen-best-of.mjs
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const A_TH = path.join(ROOT, 'astro/src/content/articles');
const A_EN = path.join(ROOT, 'astro/src/content/articles-en');
const PUB = path.join(ROOT, 'astro/public');
const DATE = '2026-06-21';
const hasThai = (s) => /[ก-฾เ-๛]/.test(s);

const LISTS = [
{ slug: 'best-islands-snorkeling-thailand', hero: 'koh-lipe', emoji: '🤿',
  th: { eyebrow: 'เกาะ & ดำน้ำ', h1: 'เกาะไหนน้ำใส<br>ดำน้ำสวยที่สุด', title: 'เกาะไหนน้ำใสดำน้ำตื้นสวยที่สุดในไทย 2026 — 6 เกาะที่เลือกได้เลย | ThailandAddict',
    metaDesc: 'อยากดำน้ำตื้นน้ำใส ๆ ในไทยไปเกาะไหนดี? รวม 6 เกาะ/จุดน้ำใสที่สุด เหลีเป๊ะ ตรัง สิมิลัน เกาะกูด เกาะหมาก เกาะเต่า พร้อมที่พักแต่ละที่',
    intro: 'รวมเกาะและจุดดำน้ำตื้น-ลึกที่น้ำใสที่สุดในไทย เลือกตามฝั่งทะเลและสไตล์ พร้อมลิงก์ที่พักของแต่ละที่',
    quick: '<strong>คำตอบสั้น ๆ:</strong> ฝั่งอันดามันน้ำใสสุดคือ <strong>เกาะหลีเป๊ะ</strong> และหมู่เกาะ <strong>สิมิลัน</strong> (ออกจากเขาหลัก) ส่วน <strong>ตรัง</strong> (เกาะกระดาน-เกาะไหง) น้ำใสและมีถ้ำมรกต ฝั่งตะวันออก <strong>เกาะกูด-เกาะหมาก</strong> น้ำนิ่งใส ส่วนสายดำน้ำลึก <strong>เกาะเต่า</strong> (ออกจากชุมพร) คือเมกกะของนักดำน้ำ' },
  en: { eyebrow: 'Islands & snorkeling', h1: 'Clearest water,<br>best snorkeling islands', title: 'Best Islands for Snorkeling & Clear Water in Thailand 2026 — 6 Picks | ThailandAddict',
    metaDesc: 'Where to snorkel in clear water in Thailand? Six of the clearest islands and dive spots — Koh Lipe, Trang, the Similans, Koh Kood, Koh Mak and Koh Tao — with where to stay at each.',
    intro: 'The clearest-water islands and snorkel/dive spots in Thailand, sorted by coast and style, each with a link to where to stay.',
    quick: '<strong>Short answer:</strong> On the Andaman side the clearest water is at <strong>Koh Lipe</strong> and the <strong>Similan Islands</strong> (from Khao Lak), while <strong>Trang</strong> (Koh Kradan/Koh Ngai) has clear water and the Emerald Cave. On the east, <strong>Koh Kood and Koh Mak</strong> have calm, clear water; for serious diving, <strong>Koh Tao</strong> (from Chumphon) is the mecca.' },
  items: [
    { name: { th: 'เกาะหลีเป๊ะ (สตูล)', en: 'Koh Lipe (Satun)' }, href: 'city-koh-lipe.html', stayHref: 'where-to-stay-koh-lipe.html',
      blurb: { th: 'น้ำใสสุดของอันดามันใต้ หาดทรายขาวละเอียด ดำน้ำตื้นรอบเกาะได้เลย มีวอล์กกิงสตรีทและรีสอร์ตครบ', en: 'The clearest water in the lower Andaman, with fine white sand and snorkeling right off the island, plus a walking street and resorts.' },
      tags: { th: ['น้ำใสสุด', 'ดำน้ำตื้นรอบเกาะ'], en: ['Clearest water', 'Snorkel off the beach'] } },
    { name: { th: 'หมู่เกาะสิมิลัน (เขาหลัก/พังงา)', en: 'Similan Islands (Khao Lak)' }, href: 'city-phang-nga.html', stayHref: 'where-to-stay-khao-lak.html',
      blurb: { th: 'จุดดำน้ำระดับโลก น้ำใสมาก ปะการังสมบูรณ์ ออกเรือจากเขาหลัก เปิดราวกลาง ต.ค.–กลาง พ.ค. (ปิดหน้ามรสุม)', en: 'A world-class dive area with very clear water and healthy reefs, reached by boat from Khao Lak; open roughly mid-Oct to mid-May (closed in the monsoon).' },
      tags: { th: ['ดำน้ำลึก', 'ปะการังสมบูรณ์'], en: ['Scuba', 'Healthy reefs'] } },
    { name: { th: 'เกาะตรัง (เกาะกระดาน-เกาะไหง)', en: 'Trang Islands (Kradan/Ngai)' }, href: 'city-trang.html', stayHref: 'where-to-stay-trang.html',
      blurb: { th: 'หาดทรายขาวน้ำใส ดำน้ำตื้นสวย และมีถ้ำมรกตที่ต้องว่ายลอดเข้าไป เงียบกว่าเกาะดัง ๆ', en: 'White sand, clear water and lovely snorkeling, plus the Emerald Cave you swim into — quieter than the famous islands.' },
      tags: { th: ['ถ้ำมรกต', 'เงียบ'], en: ['Emerald Cave', 'Quiet'] } },
    { name: { th: 'เกาะกูด (ตราด)', en: 'Koh Kood (Trat)' }, href: 'city-koh-kood.html', stayHref: 'where-to-stay-koh-kood.html',
      blurb: { th: 'เกาะใหญ่ฝั่งตะวันออก น้ำใสนิ่ง ป่าเขียว น้ำตก เหมาะดำน้ำตื้นชิล ๆ และพักผ่อนเงียบ ๆ', en: 'A large east-coast island with calm, clear water, green jungle and waterfalls — great for easy snorkeling and a quiet stay.' },
      tags: { th: ['น้ำนิ่งใส', 'เงียบ-ธรรมชาติ'], en: ['Calm clear water', 'Quiet nature'] } },
    { name: { th: 'เกาะหมาก (ตราด)', en: 'Koh Mak (Trat)' }, href: 'city-koh-mak.html', stayHref: 'where-to-stay-koh-mak.html',
      blurb: { th: 'เกาะเล็กแบนปั่นจักรยานได้ น้ำใสนิ่ง หาดเงียบ ดำน้ำตื้นหน้าหาดและรอบเกาะใกล้ ๆ', en: 'A small, flat, cycle-friendly island with calm clear water and quiet beaches — snorkel off the sand and around nearby islets.' },
      tags: { th: ['น้ำนิ่ง', 'ปั่นจักรยาน'], en: ['Calm water', 'Cycling'] } },
    { name: { th: 'เกาะเต่า (ผ่านชุมพร)', en: 'Koh Tao (via Chumphon)' }, href: 'city-chumphon.html', stayHref: 'where-to-stay-chumphon.html',
      blurb: { th: 'เมกกะของนักดำน้ำลึก คอร์สดำน้ำราคาถูกและจุดดำน้ำเยอะ ออกเรือจากชุมพรสะดวกสุด', en: 'A diving mecca with cheap courses and many dive sites; the easiest gateway is by boat from Chumphon.' },
      tags: { th: ['คอร์สดำน้ำถูก', 'จุดดำน้ำเยอะ'], en: ['Cheap dive courses', 'Many sites'] } },
  ],
  faq: [
    { q: { th: 'ดำน้ำตื้นน้ำใสสุดในไทยไปเกาะไหน?', en: 'Which Thai island has the clearest water for snorkeling?' },
      a: { th: 'เกาะหลีเป๊ะ (สตูล) และหมู่เกาะสิมิลัน (ออกจากเขาหลัก) ขึ้นชื่อว่าน้ำใสที่สุด ส่วนเกาะกระดาน-เกาะไหงของตรังก็น้ำใสและคนน้อยกว่า ทั้งหมดสวยสุดช่วงไฮซีซั่นอันดามัน (พ.ย.–เม.ย.)', en: 'Koh Lipe (Satun) and the Similan Islands (from Khao Lak) are known for the clearest water, while Trang’s Koh Kradan and Koh Ngai are clear and less crowded. All are best in the Andaman high season (Nov–Apr).' } },
    { q: { th: 'หน้าฝนยังดำน้ำได้ไหม?', en: 'Can I snorkel in the rainy season?' },
      a: { th: 'ฝั่งอันดามัน (หลีเป๊ะ สิมิลัน ตรัง) คลื่นแรงและบางจุดปิดช่วง พ.ค.–ต.ค. แต่ฝั่งอ่าวไทยและตะวันออก (เกาะเต่า เกาะกูด เกาะหมาก) ยังเที่ยวได้ช่วงนั้น เพราะมรสุมคนละจังหวะ ควรเช็กสภาพอากาศก่อน', en: 'The Andaman side (Lipe, Similan, Trang) gets rough and some spots close from May–Oct, but the Gulf and east (Koh Tao, Koh Kood, Koh Mak) are still good then, as the monsoons run on different schedules — check the forecast first.' } },
    { q: { th: 'พาเด็กไปดำน้ำตื้นเกาะไหนดี?', en: 'Which island is best for snorkeling with kids?' },
      a: { th: 'เกาะกูดและเกาะหมากน้ำนิ่งใสและหาดเงียบ เหมาะพาเด็กดำน้ำตื้นหน้าหาด ส่วนหลีเป๊ะน้ำใสมากแต่บางจุดมีเรือเยอะ ควรเลือกหาดที่คลื่นเบาและใส่เสื้อชูชีพให้เด็กเสมอ', en: 'Koh Kood and Koh Mak have calm, clear water and quiet beaches, ideal for snorkeling with children off the sand. Koh Lipe is very clear but busy with boats in places — pick a calm beach and always put a life vest on kids.' } },
  ],
},
{ slug: 'best-family-beaches-thailand', hero: 'huahin', emoji: '👨‍👩‍👧',
  th: { eyebrow: 'ทะเล & ครอบครัว', h1: 'ทะเลไหนเหมาะ<br>พาครอบครัวเที่ยว', title: 'ทะเลไหนเหมาะครอบครัวที่สุดในไทย 2026 — 6 ที่หาดเงียบ ปลอดภัย | ThailandAddict',
    metaDesc: 'พาครอบครัวเที่ยวทะเลไปไหนดี? รวม 6 ที่หาดยาว คลื่นเบา ปลอดภัย เหมาะเด็ก หัวหิน ชะอำ เขาหลัก อ่าวนาง สมุย เกาะเสม็ด พร้อมที่พัก',
    intro: 'รวมจุดหมายทะเลที่เหมาะพาครอบครัว — หาดเงียบ คลื่นเบา ปลอดภัย และมีรีสอร์ตเหมาะเด็ก พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> ใกล้กรุงเทพและสะดวกสุดคือ <strong>หัวหิน-ชะอำ</strong> (หาดยาว เมืองปลอดภัย) สายอันดามันเลือก <strong>เขาหลัก</strong> (คลื่นเบา รีสอร์ตเด็ก) หรือ <strong>อ่าวนาง</strong> (ออกทัวร์เกาะง่าย) สายเกาะใกล้กรุงเลือก <strong>เกาะเสม็ด (ระยอง)</strong> ส่วนสมุยเลือกโซนเงียบอย่างแม่น้ำ-เชิงมน' },
  en: { eyebrow: 'Beaches & family', h1: 'Best beaches<br>for families', title: 'Best Family Beaches in Thailand 2026 — 6 Calm, Safe Picks | ThailandAddict',
    metaDesc: 'Where to take the family to the beach in Thailand? Six calm, safe, kid-friendly spots — Hua Hin, Cha-am, Khao Lak, Ao Nang, Samui and Koh Samet — with where to stay.',
    intro: 'The best beach destinations for families — calm, gentle, safe and with kid-friendly resorts, each with where to stay.',
    quick: '<strong>Short answer:</strong> Closest to Bangkok and easiest are <strong>Hua Hin–Cha-am</strong> (long beaches, safe towns); on the Andaman pick <strong>Khao Lak</strong> (gentle surf, family resorts) or <strong>Ao Nang</strong> (easy island tours); for an island near Bangkok choose <strong>Koh Samet (Rayong)</strong>; on Samui, pick a quiet zone like Maenam or Choeng Mon.' },
  items: [
    { name: { th: 'หัวหิน', en: 'Hua Hin' }, href: 'city-huahin.html', stayHref: 'where-to-stay-huahin.html',
      blurb: { th: 'เมืองชายทะเลปลอดภัยใกล้กรุงเทพ หาดยาว สวนน้ำ ตลาด และรีสอร์ตครอบครัวเยอะ เที่ยวได้ทั้งปี', en: 'A safe seaside town near Bangkok with long beaches, water parks, markets and lots of family resorts — good year-round.' },
      tags: { th: ['ใกล้กรุงเทพ', 'สวนน้ำ-ตลาด'], en: ['Near Bangkok', 'Water parks & markets'] } },
    { name: { th: 'ชะอำ (เพชรบุรี)', en: 'Cha-am (Phetchaburi)' }, href: 'where-to-stay-cha-am.html', stayHref: 'where-to-stay-cha-am.html',
      blurb: { th: 'เมืองตากอากาศครอบครัวไทย หาดยาวคลื่นเบา ร้านอาหารทะเลริมหาด ราคาย่อมเยากว่าหัวหิน', en: 'A Thai family beach town with a long, gentle beach, seafront seafood and better value than Hua Hin.' },
      tags: { th: ['คลื่นเบา', 'ราคาดี'], en: ['Gentle surf', 'Good value'] } },
    { name: { th: 'เขาหลัก (พังงา)', en: 'Khao Lak (Phang Nga)' }, href: 'where-to-stay-khao-lak.html', stayHref: 'where-to-stay-khao-lak.html',
      blurb: { th: 'หาดยาวเงียบ คลื่นไม่แรงในไฮซีซั่น รีสอร์ตหลายแห่งมีสระและกิจกรรมเด็ก เหมาะพักยาว', en: 'Long, quiet beaches with gentle high-season surf and many resorts with pools and kids’ activities — good for a longer stay.' },
      tags: { th: ['หาดเงียบ', 'รีสอร์ตเด็ก'], en: ['Quiet beach', 'Family resorts'] } },
    { name: { th: 'อ่าวนาง (กระบี่)', en: 'Ao Nang (Krabi)' }, href: 'where-to-stay-ao-nang.html', stayHref: 'where-to-stay-ao-nang.html',
      blurb: { th: 'ศูนย์กลางที่พักกระบี่ เดินถึงหาดและร้าน ออกทัวร์ 4 เกาะแบบครึ่งวันได้ เหมาะครอบครัวที่อยากเที่ยวเกาะ', en: 'Krabi’s accommodation hub — walk to the beach and restaurants and take half-day 4-Islands tours, good for families who want island trips.' },
      tags: { th: ['ทัวร์เกาะง่าย', 'เดินถึงทุกอย่าง'], en: ['Easy island tours', 'Walkable'] } },
    { name: { th: 'เกาะสมุย (แม่น้ำ/เชิงมน)', en: 'Koh Samui (Maenam/Choeng Mon)' }, href: 'where-to-stay-samui.html', stayHref: 'where-to-stay-samui.html',
      blurb: { th: 'เลือกหาดเงียบอย่างแม่น้ำหรือเชิงมน น้ำตื้นนิ่ง เหมาะเด็กเล็ก มีรีสอร์ตครอบครัวและสนามบินบนเกาะ', en: 'Choose a calm beach like Maenam or Choeng Mon — shallow, still water for young children, with family resorts and an island airport.' },
      tags: { th: ['น้ำตื้นนิ่ง', 'บินตรง'], en: ['Calm shallows', 'Island airport'] } },
    { name: { th: 'เกาะเสม็ด (ระยอง)', en: 'Koh Samet (Rayong)' }, href: 'city-rayong.html', stayHref: 'where-to-stay-rayong.html',
      blurb: { th: 'เกาะทะเลใกล้กรุงเทพสุด หาดทรายขาวน้ำใส ต่อเรือจากบ้านเพสั้น ๆ เหมาะหนีกรุงสุดสัปดาห์กับครอบครัว', en: 'The closest island beach to Bangkok, with white sand and clear water, a short ferry from Ban Phe — great for a family weekend escape.' },
      tags: { th: ['ใกล้กรุงเทพ', 'เรือสั้น'], en: ['Near Bangkok', 'Short ferry'] } },
  ],
  faq: [
    { q: { th: 'พาเด็กเล็กเที่ยวทะเลที่ไหนปลอดภัยสุด?', en: 'Where is safest for a beach trip with young kids?' },
      a: { th: 'หัวหินและชะอำเป็นเมืองชายทะเลที่ปลอดภัยและสะดวกสุดสำหรับครอบครัว หาดยาวคลื่นเบา มีโรงพยาบาล ร้านค้า และสวนน้ำ ใกล้กรุงเทพขับรถถึงง่าย', en: 'Hua Hin and Cha-am are the safest, most convenient seaside towns for families — long, gentle beaches with hospitals, shops and water parks, and an easy drive from Bangkok.' } },
    { q: { th: 'ทะเลใกล้กรุงเทพไปเช้า-เย็นกลับได้ไหม?', en: 'Is there a beach near Bangkok for a day trip?' },
      a: { th: 'บางแสน (ชลบุรี) และหัวหินไปเช้า-เย็นกลับได้ ส่วนเกาะเสม็ดควรค้าง 1 คืนเพราะต้องต่อเรือ ทุกที่ห่างกรุงเทพราว 1.5–3 ชั่วโมง', en: 'Bang Saen (Chonburi) and Hua Hin work as day trips, while Koh Samet is better with one overnight as it needs a ferry; all are about 1.5–3 hours from Bangkok.' } },
    { q: { th: 'ไปทะเลครอบครัวหน้าไหนดี?', en: 'What season is best for a family beach trip?' },
      a: { th: 'อ่าวไทย (หัวหิน ชะอำ สมุย เสม็ด) สวยช่วง ก.พ.–มิ.ย. ส่วนอันดามัน (เขาหลัก อ่าวนาง) สวยสุด พ.ย.–เม.ย. หลีกเลี่ยงช่วงมรสุมของแต่ละฝั่งที่คลื่นแรง', en: 'The Gulf (Hua Hin, Cha-am, Samui, Samet) is lovely Feb–Jun, while the Andaman (Khao Lak, Ao Nang) is best Nov–Apr; avoid each coast’s monsoon months when the surf is rough.' } },
  ],
},
{ slug: 'best-cool-season-mountains-thailand', hero: 'pai', emoji: '🏔️',
  th: { eyebrow: 'ภูเขา & หน้าหนาว', h1: 'เที่ยวหน้าหนาว<br>ภูเขาไหนดี', title: 'เที่ยวหน้าหนาวภูเขาไหนดีในไทย 2026 — 6 ที่อากาศเย็น ทะเลหมอก | ThailandAddict',
    metaDesc: 'หน้าหนาวอยากไปภูเขาอากาศเย็น ทะเลหมอก ไปไหนดี? รวม 6 ที่ ปาย น่าน แม่ฮ่องสอน เชียงคาน เขาค้อ เชียงราย พร้อมที่พัก',
    intro: 'รวมจุดหมายภูเขาที่อากาศเย็นและทะเลหมอกสวยช่วงหน้าหนาว เลือกตามภาคและสไตล์ พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายเหนือเลือก <strong>ปาย</strong> (หมอก-วิวง่าย) <strong>แม่ฮ่องสอน</strong> (ปางอุ๋ง) หรือ <strong>น่าน</strong> (ดอยภูคา-ปัว) สายอีสานบนเลือก <strong>เชียงคาน (เลย)</strong> ริมโขง ส่วนภาคกลางตอนบน <strong>เขาค้อ (เพชรบูรณ์)</strong> ทะเลหมอกใกล้กรุงเทพสุด' },
  en: { eyebrow: 'Mountains & cool season', h1: 'Cool-season<br>mountain escapes', title: 'Best Cool-Season Mountain Trips in Thailand 2026 — 6 Misty Picks | ThailandAddict',
    metaDesc: 'Where to go for cool air and a sea of mist in Thailand’s cool season? Six picks — Pai, Nan, Mae Hong Son, Chiang Khan, Khao Kho and Chiang Rai — with where to stay.',
    intro: 'The best mountain destinations for cool air and morning mist in the cool season, sorted by region and style, each with where to stay.',
    quick: '<strong>Short answer:</strong> In the north choose <strong>Pai</strong> (easy mist and views), <strong>Mae Hong Son</strong> (Pang Ung) or <strong>Nan</strong> (Doi Phu Kha/Pua); in the upper Isan, <strong>Chiang Khan (Loei)</strong> on the Mekong; and for the sea of mist closest to Bangkok, <strong>Khao Kho (Phetchabun)</strong>.' },
  items: [
    { name: { th: 'ปาย (แม่ฮ่องสอน)', en: 'Pai (Mae Hong Son)' }, href: 'city-pai.html', stayHref: 'where-to-stay-pai.html',
      blurb: { th: 'เมืองเล็กในหุบเขา อากาศเย็น ทะเลหมอกดูง่าย คาเฟ่ชิล ๆ และถนนคนเดินกลางคืน เหมาะมาครั้งแรกสายภูเขา', en: 'A small town in a valley — cool air, easy-to-see mist, laid-back cafés and a night walking street, perfect for a first mountain trip.' },
      tags: { th: ['ทะเลหมอกง่าย', 'คาเฟ่'], en: ['Easy mist', 'Cafés'] } },
    { name: { th: 'แม่ฮ่องสอน', en: 'Mae Hong Son' }, href: 'city-mae-hong-son.html', stayHref: 'where-to-stay-mae-hong-son.html',
      blurb: { th: 'เมืองหุบเขาหมอกหนา ปางอุ๋งและบ้านรักไทยวิวทะเลสาบหมอกยามเช้า เหมาะสายขับรถลูป 1,864 โค้ง', en: 'A misty valley town — Pang Ung and Ban Rak Thai offer dawn mist over the lake, and it anchors the 1,864-curve loop drive.' },
      tags: { th: ['ปางอุ๋ง', 'ลูปแม่ฮ่องสอน'], en: ['Pang Ung', 'The MHS loop'] } },
    { name: { th: 'น่าน', en: 'Nan' }, href: 'city-nan.html', stayHref: 'where-to-stay-nan.html',
      blurb: { th: 'เมืองเก่าเงียบ ๆ + ภูเขา ขึ้นปัว-ดอยภูคาชมวิวนาขั้นบันไดและทะเลหมอก คาเฟ่วิวเขาสวย', en: 'A quiet old town plus mountains — head to Pua and Doi Phu Kha for terraced fields, mist and scenic mountain cafés.' },
      tags: { th: ['ดอยภูคา', 'นาขั้นบันได'], en: ['Doi Phu Kha', 'Terraced fields'] } },
    { name: { th: 'เชียงคาน (เลย)', en: 'Chiang Khan (Loei)' }, href: 'where-to-stay-chiang-khan.html', stayHref: 'where-to-stay-chiang-khan.html',
      blurb: { th: 'เมืองริมโขงบ้านไม้เก่า อากาศเย็น ตักบาตรข้าวเหนียวเช้า ทะเลหมอกที่ภูทอก หน้าหนาวคนเยอะจองล่วงหน้า', en: 'A Mekong town of old wooden houses — cool air, dawn sticky-rice alms and mist at Phu Thok; it is busy in winter, so book ahead.' },
      tags: { th: ['ริมโขง', 'ตักบาตรเช้า'], en: ['Mekong town', 'Dawn alms'] } },
    { name: { th: 'เขาค้อ (เพชรบูรณ์)', en: 'Khao Kho (Phetchabun)' }, href: 'where-to-stay-phetchabun.html', stayHref: 'where-to-stay-phetchabun.html',
      blurb: { th: '“สวิตเซอร์แลนด์เมืองไทย” ทะเลหมอกใกล้กรุงเทพสุด รีสอร์ตวิวเขาเยอะ ขับรถถึงง่าย เหมาะสุดสัปดาห์', en: 'The “Switzerland of Thailand” — the sea of mist closest to Bangkok, with many hill-view resorts and an easy drive, great for a weekend.' },
      tags: { th: ['ใกล้กรุงเทพ', 'รีสอร์ตวิวเขา'], en: ['Near Bangkok', 'Hill-view resorts'] } },
    { name: { th: 'เชียงราย', en: 'Chiang Rai' }, href: 'city-chiang-rai.html', stayHref: 'where-to-stay-chiang-rai.html',
      blurb: { th: 'เหนือสุด อากาศเย็น ไร่ชา ดอยตุง ดอยช้าง วัดสวย และทะเลหมอกที่ภูชี้ฟ้า เที่ยวได้หลายวัน', en: 'The far north — cool air, tea plantations, Doi Tung and Doi Chang, beautiful temples and the mist at Phu Chi Fa, good for several days.' },
      tags: { th: ['ไร่ชา', 'ภูชี้ฟ้า'], en: ['Tea farms', 'Phu Chi Fa'] } },
  ],
  faq: [
    { q: { th: 'หน้าหนาวไทยภูเขาที่ไหนหนาวสุด?', en: 'Where is coldest in Thailand’s cool season?' },
      a: { th: 'ยอดเขาสูงอย่างภูทับเบิก (เพชรบูรณ์) ดอยอินทนนท์ (เชียงใหม่) และดอยสูงในเชียงราย-แม่ฮ่องสอน หนาวสุด บางวันใกล้ 0 องศา ช่วงหนาวจัดคือ ธ.ค.–ม.ค. ควรเตรียมเสื้อกันหนาว', en: 'High summits like Phu Thap Boek (Phetchabun), Doi Inthanon (Chiang Mai) and the high peaks of Chiang Rai/Mae Hong Son are coldest, sometimes near 0°C; the deepest cold is Dec–Jan, so pack warm layers.' } },
    { q: { th: 'ไปดูทะเลหมอกควรไปเดือนไหน?', en: 'When should I go to see the sea of mist?' },
      a: { th: 'พ.ย.–ก.พ. คือช่วงทะเลหมอกหนาและอากาศเย็นสุด ควรตื่นเช้ามืดไปจุดชมวิวก่อนพระอาทิตย์ขึ้น วันหยุดยาวคนเยอะและที่พักเต็มเร็ว ควรจองล่วงหน้า', en: 'Nov–Feb has the thickest mist and coolest air; head to the viewpoint before sunrise. Long weekends are crowded and rooms sell out fast, so book ahead.' } },
    { q: { th: 'ไม่มีรถเที่ยวภูเขาได้ไหม?', en: 'Can I visit the mountains without a car?' },
      a: { th: 'ปายและเชียงคานเที่ยวได้สบายแบบไม่มีรถ เพราะตัวเมืองเดินได้และมีรถเช่า/ทัวร์ ส่วนน่าน เขาค้อ และแม่ฮ่องสอนตอนนอกเมืองควรมีรถหรือเช่ามอเตอร์ไซค์เพราะที่เที่ยวกระจาย', en: 'Pai and Chiang Khan are easy without a car — the towns are walkable with rentals and tours — while the outskirts of Nan, Khao Kho and Mae Hong Son really need a car or motorbike, as the sights are spread out.' } },
  ],
},
{ slug: 'best-honeymoon-escapes-thailand', hero: 'koh-kood', emoji: '💛',
  th: { eyebrow: 'ฮันนีมูน & เงียบ', h1: 'ฮันนีมูนเงียบ ๆ<br>ไปที่ไหนดี', title: 'ฮันนีมูนเงียบ ๆ ในไทยไปไหนดี 2026 — 6 ที่โรแมนติก น้ำใส | ThailandAddict',
    metaDesc: 'ฮันนีมูนหรือทริปคู่รักอยากได้ที่เงียบ ๆ โรแมนติก ไปไหนดี? รวม 6 ที่ เกาะกูด เกาะหมาก เขาหลัก ไร่เลย์ สมุย หลีเป๊ะ พร้อมที่พัก',
    intro: 'รวมจุดหมายเงียบ ๆ โรแมนติก เหมาะฮันนีมูนและทริปคู่รัก หาดสวย น้ำใส รีสอร์ตเป็นส่วนตัว พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายเกาะเงียบน้ำใสเลือก <strong>เกาะกูด</strong> หรือ <strong>เกาะหมาก</strong> (ตราด) สายหรู-เงียบเลือก <strong>เขาหลัก (คึกคัก)</strong> สายวิวหน้าผาดราม่าเลือก <strong>ไร่เลย์/หาดพระนาง</strong> สายเกาะใต้น้ำใสเลือก <strong>หลีเป๊ะ</strong> ส่วนสมุยเลือกอ่าวเงียบอย่างเฉวงน้อย' },
  en: { eyebrow: 'Honeymoon & quiet', h1: 'Quiet honeymoon<br>escapes', title: 'Best Quiet Honeymoon Escapes in Thailand 2026 — 6 Romantic Picks | ThailandAddict',
    metaDesc: 'Looking for a quiet, romantic honeymoon spot in Thailand? Six picks — Koh Kood, Koh Mak, Khao Lak, Railay, Samui and Koh Lipe — with where to stay.',
    intro: 'Quiet, romantic destinations for honeymoons and couples — lovely beaches, clear water and private resorts, each with where to stay.',
    quick: '<strong>Short answer:</strong> For quiet, clear-water islands choose <strong>Koh Kood</strong> or <strong>Koh Mak</strong> (Trat); for quiet luxury, <strong>Khao Lak (Khuk Khak)</strong>; for dramatic cliff scenery, <strong>Railay/Phra Nang</strong>; for a clear-water southern island, <strong>Koh Lipe</strong>; on Samui, a quiet cove like Chaweng Noi.' },
  items: [
    { name: { th: 'เกาะกูด (ตราด)', en: 'Koh Kood (Trat)' }, href: 'city-koh-kood.html', stayHref: 'where-to-stay-koh-kood.html',
      blurb: { th: 'น้ำใสนิ่ง ป่าเขียว หาดเงียบ รีสอร์ตวิวพระอาทิตย์ตก ไม่มีไนต์ไลฟ์ เหมาะพักผ่อนสองคนจริง ๆ', en: 'Calm clear water, green jungle, quiet beaches and sunset-view resorts with no nightlife — a true two-person retreat.' },
      tags: { th: ['น้ำใส', 'ไม่มีไนต์ไลฟ์'], en: ['Clear water', 'No nightlife'] } },
    { name: { th: 'เกาะหมาก (ตราด)', en: 'Koh Mak (Trat)' }, href: 'city-koh-mak.html', stayHref: 'where-to-stay-koh-mak.html',
      blurb: { th: 'เกาะเล็กเงียบ ปั่นจักรยานเที่ยวด้วยกัน น้ำนิ่งใส พระอาทิตย์ตกสวย เจ้าของรีสอร์ตเป็นกันเอง', en: 'A small, quiet island to cycle together, with calm clear water, lovely sunsets and friendly resort owners.' },
      tags: { th: ['เงียบ', 'พระอาทิตย์ตก'], en: ['Quiet', 'Sunsets'] } },
    { name: { th: 'เขาหลัก (พังงา)', en: 'Khao Lak (Phang Nga)' }, href: 'where-to-stay-khao-lak.html', stayHref: 'where-to-stay-khao-lak.html',
      blurb: { th: 'โซนคึกคัก-บางสักทางเหนือเงียบและรีสอร์ตหรู หาดยาวเป็นส่วนตัว ใกล้สิมิลัน เหมาะคู่รักสายชิล', en: 'The Khuk Khak/Bang Sak stretch to the north is quiet with upscale resorts, private long beaches and the Similans nearby — great for laid-back couples.' },
      tags: { th: ['หรู-เงียบ', 'ใกล้สิมิลัน'], en: ['Quiet luxury', 'Near the Similans'] } },
    { name: { th: 'ไร่เลย์ / หาดพระนาง (กระบี่)', en: 'Railay / Phra Nang (Krabi)' }, href: 'where-to-stay-railay.html', stayHref: 'where-to-stay-railay.html',
      blurb: { th: 'หน้าผาหินปูนดราม่า เข้าได้ด้วยเรือเท่านั้น หาดพระนางสวยมาก บรรยากาศโรแมนติกและเป็นส่วนตัว', en: 'Dramatic limestone cliffs reached only by boat, with the stunning Phra Nang beach — romantic and private.' },
      tags: { th: ['วิวหน้าผา', 'เข้าด้วยเรือ'], en: ['Cliff views', 'Boat-access'] } },
    { name: { th: 'เกาะสมุย (เฉวงน้อย/บ่อผุด)', en: 'Koh Samui (Chaweng Noi/Bophut)' }, href: 'where-to-stay-samui.html', stayHref: 'where-to-stay-chaweng.html',
      blurb: { th: 'เลือกอ่าวเงียบอย่างเฉวงน้อยหรือบ่อผุด รีสอร์ตหรู ดินเนอร์ริมหาด และบินตรงถึงเกาะ สะดวกสำหรับคู่รัก', en: 'Pick a quiet cove like Chaweng Noi or Bophut — luxury resorts, beachfront dinners and direct flights to the island, convenient for couples.' },
      tags: { th: ['รีสอร์ตหรู', 'บินตรง'], en: ['Luxury resorts', 'Direct flights'] } },
    { name: { th: 'เกาะหลีเป๊ะ (สตูล)', en: 'Koh Lipe (Satun)' }, href: 'city-koh-lipe.html', stayHref: 'where-to-stay-koh-lipe.html',
      blurb: { th: 'น้ำใสที่สุดของอันดามันใต้ หาดทรายขาว พระอาทิตย์ตกสวย รีสอร์ตติดหาดให้เลือก เหมาะคู่รักสายทะเล', en: 'The clearest water in the lower Andaman, white sand and fine sunsets, with beachfront resorts — ideal for sea-loving couples.' },
      tags: { th: ['น้ำใสสุด', 'พระอาทิตย์ตก'], en: ['Clearest water', 'Sunsets'] } },
  ],
  faq: [
    { q: { th: 'ฮันนีมูนอยากได้เกาะเงียบที่สุดไปไหน?', en: 'Which island is quietest for a honeymoon?' },
      a: { th: 'เกาะกูดและเกาะหมาก (ตราด) เงียบและเป็นส่วนตัวที่สุด ไม่มีไนต์ไลฟ์ น้ำใสนิ่ง เหมาะพักผ่อนสองคน ส่วนถ้าอยากได้น้ำใสสุดเลือกหลีเป๊ะแต่จะคึกคักกว่าเล็กน้อย', en: 'Koh Kood and Koh Mak (Trat) are the quietest and most private, with no nightlife and calm clear water — ideal for two. For the clearest water, Koh Lipe is a touch livelier but stunning.' } },
    { q: { th: 'ฮันนีมูนไทยไปหน้าไหนดี?', en: 'What is the best season for a Thailand honeymoon?' },
      a: { th: 'อันดามัน (เขาหลัก ไร่เลย์ หลีเป๊ะ) สวยสุด พ.ย.–เม.ย. ส่วนฝั่งตะวันออก (เกาะกูด เกาะหมาก) และอ่าวไทย (สมุย) เลี่ยงช่วงมรสุมของแต่ละฝั่ง โดยรวมเดือน ม.ค.–มี.ค. อากาศดีเกือบทุกที่', en: 'The Andaman (Khao Lak, Railay, Lipe) is best Nov–Apr, while the east (Koh Kood, Koh Mak) and the Gulf (Samui) avoid their own monsoon months; overall, Jan–Mar is good almost everywhere.' } },
    { q: { th: 'ฮันนีมูนงบไม่สูงไปเกาะไหนได้บ้าง?', en: 'Any budget-friendly honeymoon islands?' },
      a: { th: 'เกาะหมากและเกาะกูดมีรีสอร์ตหลายระดับ เลือกบังกะโลริมหาดราคาเบาได้ ส่วนหลีเป๊ะนอกไฮซีซั่นราคาลดเยอะ จองล่วงหน้าและเลี่ยงวันหยุดยาวจะได้ราคาดีกว่า', en: 'Koh Mak and Koh Kood have resorts at a range of prices, including affordable beachfront bungalows, and Koh Lipe drops a lot outside high season — book ahead and avoid long weekends for better rates.' } },
  ],
},
{ slug: 'best-nightlife-thailand', hero: 'koh-phangan', emoji: '🎉',
  th: { eyebrow: 'ไนต์ไลฟ์ & ปาร์ตี้', h1: 'สายปาร์ตี้<br>ไปเที่ยวไหนดี', title: 'เที่ยวกลางคืน-ปาร์ตี้ที่ไหนดีในไทย 2026 — 5 ที่ไนต์ไลฟ์เด็ด | ThailandAddict',
    metaDesc: 'สายปาร์ตี้-ไนต์ไลฟ์ในไทยไปไหนดี? รวม 5 ที่ เกาะพะงัน (ฟูลมูน) ภูเก็ตป่าตอง พัทยา เกาะสมุยเฉวง และกรุงเทพ พร้อมที่พัก',
    intro: 'รวมจุดหมายไนต์ไลฟ์-ปาร์ตี้ที่ดังที่สุดในไทย เลือกตามสไตล์ ตั้งแต่ฟูลมูนถึงรูฟท็อปบาร์ พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายปาร์ตี้ทะเลเลือก <strong>เกาะพะงัน</strong> (ฟูลมูนปาร์ตี้) สายหาด+ไนต์ไลฟ์เลือก <strong>ภูเก็ต (ป่าตอง/บางลา)</strong> หรือ <strong>พัทยา (วอล์กกิงสตรีท)</strong> สายบีชคลับเลือก <strong>เกาะสมุย (เฉวง)</strong> ส่วนสายรูฟท็อป-คลับเลือก <strong>กรุงเทพ</strong> (สุขุมวิท/สีลม)' },
  en: { eyebrow: 'Nightlife & parties', h1: 'Where to party<br>in Thailand', title: 'Best Nightlife & Party Spots in Thailand 2026 — 5 Picks | ThailandAddict',
    metaDesc: 'Where is the best nightlife in Thailand? Five picks — Koh Phangan (Full Moon), Phuket Patong, Pattaya, Koh Samui Chaweng and Bangkok — with where to stay.',
    intro: 'Thailand’s biggest nightlife and party destinations, from Full Moon beaches to rooftop bars, sorted by style, each with where to stay.',
    quick: '<strong>Short answer:</strong> For a beach party choose <strong>Koh Phangan</strong> (the Full Moon Party); for beach plus nightlife, <strong>Phuket (Patong/Bangla)</strong> or <strong>Pattaya (Walking Street)</strong>; for beach clubs, <strong>Koh Samui (Chaweng)</strong>; for rooftops and clubs, <strong>Bangkok</strong> (Sukhumvit/Silom).' },
  items: [
    { name: { th: 'เกาะพะงัน', en: 'Koh Phangan' }, href: 'city-koh-phangan.html', stayHref: 'where-to-stay-koh-phangan.html',
      blurb: { th: 'บ้านเกิดฟูลมูนปาร์ตี้ที่หาดริ้น คืนปาร์ตี้คนทั่วโลกมารวมตัว มีฮาล์ฟมูนและจังเกิลปาร์ตี้ด้วย', en: 'Home of the Full Moon Party at Haad Rin, where a global crowd gathers on party nights, plus Half Moon and jungle parties.' },
      tags: { th: ['ฟูลมูนปาร์ตี้', 'หาดริ้น'], en: ['Full Moon Party', 'Haad Rin'] } },
    { name: { th: 'ภูเก็ต (ป่าตอง)', en: 'Phuket (Patong)' }, href: 'where-to-stay-patong.html', stayHref: 'where-to-stay-patong.html',
      blurb: { th: 'ถนนบางลาคือศูนย์กลางไนต์ไลฟ์ภูเก็ต บาร์ คลับ และโชว์ครบ ติดหาดป่าตอง เดินถึงทุกอย่าง', en: 'Bangla Road is Phuket’s nightlife hub — bars, clubs and shows, right by Patong beach and all within walking distance.' },
      tags: { th: ['ถนนบางลา', 'ติดหาด'], en: ['Bangla Road', 'On the beach'] } },
    { name: { th: 'พัทยา', en: 'Pattaya' }, href: 'city-pattaya.html', stayHref: 'where-to-stay-pattaya.html',
      blurb: { th: 'วอล์กกิงสตรีทไนต์ไลฟ์แน่น ใกล้กรุงเทพสุด มีทั้งบาร์ คลับ บีชคลับ และโชว์ เที่ยวกลางคืนได้ทั้งปี', en: 'Walking Street packs the nightlife and it is closest to Bangkok, with bars, clubs, beach clubs and shows — a year-round night out.' },
      tags: { th: ['วอล์กกิงสตรีท', 'ใกล้กรุงเทพ'], en: ['Walking Street', 'Near Bangkok'] } },
    { name: { th: 'เกาะสมุย (เฉวง)', en: 'Koh Samui (Chaweng)' }, href: 'where-to-stay-chaweng.html', stayHref: 'where-to-stay-chaweng.html',
      blurb: { th: 'หาดเฉวงมีบีชคลับ บาร์ และคลับริมหาด บรรยากาศหรูกว่าฟูลมูน เหมาะสายปาร์ตี้ที่อยากได้หาดสวยด้วย', en: 'Chaweng has beach clubs, bars and seaside clubs with a more upscale feel than the Full Moon scene — for partygoers who also want a nice beach.' },
      tags: { th: ['บีชคลับ', 'หาดสวย'], en: ['Beach clubs', 'Nice beach'] } },
    { name: { th: 'กรุงเทพ', en: 'Bangkok' }, href: 'city-bangkok.html', stayHref: 'where-to-stay-bangkok.html',
      blurb: { th: 'รูฟท็อปบาร์วิวเมือง คลับระดับโลก และไนต์ไลฟ์สุขุมวิท-สีลม-ทองหล่อ ครบทุกแนวในเมืองเดียว', en: 'Rooftop bars with city views, world-class clubs and the Sukhumvit–Silom–Thong Lo scene — every style in one city.' },
      tags: { th: ['รูฟท็อปบาร์', 'คลับ'], en: ['Rooftop bars', 'Clubs'] } },
  ],
  faq: [
    { q: { th: 'ฟูลมูนปาร์ตี้จัดที่ไหน เมื่อไหร่?', en: 'Where and when is the Full Moon Party?' },
      a: { th: 'จัดที่หาดริ้น เกาะพะงัน คืนวันเพ็ญ (พระจันทร์เต็มดวง) ทุกเดือน บางเดือนเลื่อนเลี่ยงวันพระ ที่พักเต็มเร็วและราคาขึ้นช่วงปาร์ตี้ ควรจองล่วงหน้านาน ๆ', en: 'It is held at Haad Rin on Koh Phangan on the full-moon night each month (occasionally shifted around Buddhist holy days); rooms fill fast and prices rise on party nights, so book well ahead.' } },
    { q: { th: 'สายปาร์ตี้แต่ก็อยากได้หาดสวยไปไหนดี?', en: 'Where can I party but still have a nice beach?' },
      a: { th: 'เกาะสมุย (เฉวง) และภูเก็ต (ป่าตอง) มีทั้งไนต์ไลฟ์และหาดสวยในที่เดียว ส่วนเกาะพะงันนอกคืนฟูลมูนก็มีหาดเงียบสวยทางเหนือให้พักผ่อน', en: 'Koh Samui (Chaweng) and Phuket (Patong) combine nightlife with a good beach in one place, while Koh Phangan outside Full Moon nights has quiet, pretty beaches in the north for relaxing.' } },
    { q: { th: 'เที่ยวกลางคืนใกล้กรุงเทพไปไหนดี?', en: 'Where is good nightlife near Bangkok?' },
      a: { th: 'พัทยาใกล้สุด ขับรถราว 2 ชั่วโมง มีวอล์กกิงสตรีทและบีชคลับครบ ส่วนในกรุงเทพเองมีรูฟท็อปบาร์และคลับระดับโลกย่านสุขุมวิท-สีลม เที่ยวได้ทุกคืน', en: 'Pattaya is closest, about a two-hour drive, with Walking Street and beach clubs, while Bangkok itself has rooftop bars and world-class clubs around Sukhumvit–Silom every night.' } },
  ],
},
{ slug: 'best-rainy-season-thailand', hero: 'chiang-mai', emoji: '🌧️',
  th: { eyebrow: 'หน้าฝน & เที่ยวไหนดี', h1: 'หน้าฝน<br>เที่ยวไหนดี', title: 'หน้าฝนเที่ยวไหนดีในไทย 2026 — 6 ที่เขียวสวย คนน้อย | ThailandAddict',
    metaDesc: 'หน้าฝน (พ.ค.–ต.ค.) เที่ยวไทยที่ไหนดี? รวม 6 ที่เขียวสวย น้ำตกเต็ม คนน้อย เชียงใหม่ น่าน เขาใหญ่ กาญจนบุรี อีสาน พร้อมที่พัก',
    intro: 'หน้าฝนไม่ใช่หมดสนุก — รวมจุดหมายที่เขียวสวย น้ำตกเต็ม คนน้อยและราคาดีช่วงหน้าฝน พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> หน้าฝน (พ.ค.–ต.ค.) ฝั่งอันดามันคลื่นแรง แต่ <strong>ภาคเหนือ-อีสาน-ภาคกลาง</strong> ยังเที่ยวได้ดี ฝนมักตกบ่าย-เย็น เช้าฟ้าเปิด เขียวสวยและคนน้อย เลือก <strong>เชียงใหม่ น่าน เขาใหญ่ กาญจนบุรี</strong> หรืออีสานอย่าง <strong>เลย-อุบลฯ</strong> น้ำตกเต็มสวยช่วงนี้พอดี' },
  en: { eyebrow: 'Rainy season & where to go', h1: 'Where to go<br>in the rainy season', title: 'Where to Go in Thailand’s Rainy Season 2026 — 6 Green, Quiet Picks | ThailandAddict',
    metaDesc: 'Where to travel in Thailand in the rainy season (May–Oct)? Six green, less-crowded picks — Chiang Mai, Nan, Khao Yai, Kanchanaburi and Isan — with where to stay.',
    intro: 'The rainy season is not a write-off — destinations that are green, with full waterfalls, fewer crowds and lower prices, each with where to stay.',
    quick: '<strong>Short answer:</strong> In the rainy season (May–Oct) the Andaman coast is rough, but the <strong>north, Isan and central regions</strong> are still good — rain tends to fall in the afternoon and evening with clear mornings, everything is green and crowds are thin. Choose <strong>Chiang Mai, Nan, Khao Yai, Kanchanaburi</strong> or Isan spots like <strong>Loei/Ubon</strong>, where the waterfalls are full at this time.' },
  items: [
    { name: { th: 'เชียงใหม่', en: 'Chiang Mai' }, href: 'city-chiang-mai.html', stayHref: 'where-to-stay-chiang-mai.html',
      blurb: { th: 'หน้าฝนภาคเหนือเขียวสวย ฝนมักตกบ่าย-เย็น เช้าเที่ยววัด-คาเฟ่ได้ น้ำตกและดอยเขียวชอุ่ม ราคาที่พักถูกลง', en: 'The north turns lush in the rains; showers usually fall in the afternoon, leaving mornings for temples and cafés, with green hills and waterfalls and lower room prices.' },
      tags: { th: ['เขียวสวย', 'ราคาดี'], en: ['Lush green', 'Lower prices'] } },
    { name: { th: 'น่าน', en: 'Nan' }, href: 'city-nan.html', stayHref: 'where-to-stay-nan.html',
      blurb: { th: 'นาขั้นบันไดที่ปัวเขียวสุดช่วงหน้าฝน เมืองเงียบ คนน้อย คาเฟ่วิวนา เหมาะสายชิลถ่ายรูปธรรมชาติ', en: 'The terraced fields at Pua are greenest in the rains; the town is quiet with few crowds and field-view cafés — great for slow, scenic photography.' },
      tags: { th: ['นาเขียว', 'คนน้อย'], en: ['Green fields', 'Few crowds'] } },
    { name: { th: 'เขาใหญ่', en: 'Khao Yai' }, href: 'city-khao-yai.html', stayHref: 'where-to-stay-khao-yai.html',
      blurb: { th: 'หน้าฝนป่าเขียว น้ำตกเต็ม (เหวสุวัต) สัตว์ป่าออกหากินง่าย อากาศเย็นสบาย ใกล้กรุงเทพขับรถถึงง่าย', en: 'In the rains the forest is green, waterfalls like Haew Suwat are full, wildlife is easier to spot and the air is cool — an easy drive from Bangkok.' },
      tags: { th: ['น้ำตกเต็ม', 'ใกล้กรุงเทพ'], en: ['Full waterfalls', 'Near Bangkok'] } },
    { name: { th: 'กาญจนบุรี', en: 'Kanchanaburi' }, href: 'city-kanchanaburi.html', stayHref: 'where-to-stay-kanchanaburi.html',
      blurb: { th: 'น้ำตกเอราวัณและแม่น้ำสวยสุดหน้าฝน แพริมน้ำเขียวชอุ่ม สังขละบุรีหมอกลง เหมาะสายธรรมชาติ-แพ', en: 'The Erawan waterfalls and rivers are at their best in the rains, with green riverside rafts and misty Sangkhlaburi — great for nature and raft stays.' },
      tags: { th: ['น้ำตกเอราวัณ', 'แพริมน้ำ'], en: ['Erawan Falls', 'River rafts'] } },
    { name: { th: 'เลย (ภูเรือ/เชียงคาน)', en: 'Loei (Phu Ruea/Chiang Khan)' }, href: 'city-loei.html', stayHref: 'where-to-stay-loei.html',
      blurb: { th: 'ภูเขาอีสานบนเขียวสวย น้ำตกเต็ม อากาศเย็นสบายกว่าที่ราบ ริมโขงเชียงคานบรรยากาศดี คนน้อยกว่าหน้าหนาว', en: 'The upper-Isan mountains are green with full waterfalls and cooler air than the lowlands, and Chiang Khan’s riverside is pleasant — quieter than in winter.' },
      tags: { th: ['ภูเขาเขียว', 'คนน้อย'], en: ['Green mountains', 'Fewer crowds'] } },
    { name: { th: 'อุบลราชธานี', en: 'Ubon Ratchathani' }, href: 'city-ubon-ratchathani.html', stayHref: 'where-to-stay-ubon-ratchathani.html',
      blurb: { th: 'อีสานใต้หน้าฝนเขียวสวย แม่น้ำโขงเต็ม สามพันโบกจมน้ำ (เห็นชัดหน้าแล้ง) แต่ผาแต้มและน้ำตกเต็มสวย คนน้อย', en: 'The lower Isan is green in the rains and the Mekong is full; Sam Phan Bok is submerged (best seen in the dry season), but Pha Taem and the waterfalls are full and crowds are thin.' },
      tags: { th: ['ริมโขงเต็ม', 'คนน้อย'], en: ['Full Mekong', 'Few crowds'] } },
  ],
  faq: [
    { q: { th: 'หน้าฝนไทยเที่ยวทะเลได้ไหม?', en: 'Can I still do a beach trip in the rainy season?' },
      a: { th: 'ฝั่งอันดามัน (ภูเก็ต กระบี่ หลีเป๊ะ) คลื่นแรงและฝนเยอะ พ.ค.–ต.ค. แต่ฝั่งอ่าวไทย (สมุย พะงัน หัวหิน) ยังพอเที่ยวได้ช่วงนั้นเพราะมรสุมคนละจังหวะ (อ่าวไทยฝนหนัก ต.ค.–ธ.ค.) ควรเช็กพยากรณ์ก่อน', en: 'The Andaman (Phuket, Krabi, Lipe) is rough and wet May–Oct, but the Gulf (Samui, Phangan, Hua Hin) is still workable then, as the monsoons differ (the Gulf’s heaviest rain is Oct–Dec) — check the forecast first.' } },
    { q: { th: 'หน้าฝนเที่ยวคุ้มไหม?', en: 'Is the rainy season worth traveling in?' },
      a: { th: 'คุ้มถ้าเลือกที่ถูก หน้าฝนภาคเหนือ-อีสาน-ภาคกลางเขียวสวย น้ำตกเต็ม คนน้อย และที่พักถูกลง ฝนมักตกบ่าย-เย็นไม่ทั้งวัน วางแผนเที่ยวเช้า-เผื่อร่มไว้ก็เที่ยวสนุก', en: 'It is, if you pick the right place — the north, Isan and central regions are lush, the waterfalls are full, crowds are thin and rooms are cheaper. Rain usually falls in the afternoon, not all day, so plan mornings out and carry an umbrella.' } },
    { q: { th: 'หน้าฝนดูน้ำตกที่ไหนสวย?', en: 'Where are the best waterfalls in the rainy season?' },
      a: { th: 'น้ำตกเต็มและสวยสุดช่วงหน้าฝน-ปลายฝน เช่น เอราวัณ (กาญจนบุรี) เหวสุวัต (เขาใหญ่) ทีลอซู (อุ้มผาง/ตาก) และน้ำตกในเลย-เพชรบูรณ์ ควรระวังทางลื่นและกระแสน้ำแรง', en: 'Waterfalls are fullest in and just after the rains — Erawan (Kanchanaburi), Haew Suwat (Khao Yai), Thi Lo Su (Umphang/Tak) and the falls of Loei/Phetchabun; mind slippery paths and strong currents.' } },
  ],
},
{ slug: 'best-day-trips-from-bangkok', hero: 'ayutthaya', emoji: '🚆',
  th: { eyebrow: 'เดย์ทริปใกล้กรุงเทพ', h1: 'เที่ยวใกล้กรุงเทพ<br>ไปเช้า-เย็นกลับ', title: 'เที่ยวใกล้กรุงเทพไปเช้า-เย็นกลับที่ไหนดี 2026 — 6 ที่เดย์ทริป | ThailandAddict',
    metaDesc: 'อยากไปเที่ยวใกล้กรุงเทพแบบไปเช้า-เย็นกลับไปไหนดี? รวม 6 ที่ อยุธยา กาญจนบุรี อัมพวา บางแสน เขาใหญ่ ราชบุรี พร้อมที่พักถ้าอยากค้างคืน',
    intro: 'รวมจุดหมายใกล้กรุงเทพที่ขับรถหรือนั่งรถไปเช้า-เย็นกลับได้สบาย เผื่ออยากค้างคืนก็มีลิงก์ที่พักให้',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายวัด-เมืองเก่าไป <strong>อยุธยา</strong> สายธรรมชาติ-น้ำตกไป <strong>กาญจนบุรี</strong> หรือ <strong>เขาใหญ่</strong> สายตลาดน้ำไป <strong>อัมพวา (สมุทรสงคราม)</strong> หรือ <strong>ราชบุรี (ดำเนินสะดวก)</strong> ส่วนสายทะเลใกล้สุดไป <strong>บางแสน (ชลบุรี)</strong> ทั้งหมดห่างกรุงเทพราว 1-3 ชั่วโมง' },
  en: { eyebrow: 'Day trips near Bangkok', h1: 'Day trips from<br>Bangkok', title: 'Best Day Trips from Bangkok 2026 — 6 Easy Out-and-Back Picks | ThailandAddict',
    metaDesc: 'Where to go on a day trip from Bangkok? Six easy out-and-back picks — Ayutthaya, Kanchanaburi, Amphawa, Bang Saen, Khao Yai and Ratchaburi — with where to stay if you overnight.',
    intro: 'Destinations close enough to Bangkok for an easy out-and-back day, each with a link to where to stay if you decide to overnight.',
    quick: '<strong>Short answer:</strong> For temples and old cities go to <strong>Ayutthaya</strong>; for nature and waterfalls, <strong>Kanchanaburi</strong> or <strong>Khao Yai</strong>; for floating markets, <strong>Amphawa (Samut Songkhram)</strong> or <strong>Ratchaburi (Damnoen Saduak)</strong>; and for the nearest beach, <strong>Bang Saen (Chonburi)</strong>. All are about 1–3 hours from Bangkok.' },
  items: [
    { name: { th: 'อยุธยา', en: 'Ayutthaya' }, href: 'city-ayutthaya.html', stayHref: 'where-to-stay-ayutthaya.html',
      blurb: { th: 'อดีตราชธานีเก่าแก่ เต็มไปด้วยวัดและเจดีย์โบราณ ขับรถหรือนั่งรถไฟจากกรุงเทพราว 1.5 ชั่วโมง เช่าจักรยานหรือนั่งรถชมโบราณสถานได้ในวันเดียว', en: 'The old royal capital, full of ancient temples and stupas, about 1.5 hours from Bangkok by car or train — rent a bike or hop a tuk-tuk to see the ruins in a day.' },
      tags: { th: ['วัด-โบราณสถาน', 'นั่งรถไฟได้'], en: ['Temple ruins', 'Reachable by train'] } },
    { name: { th: 'กาญจนบุรี', en: 'Kanchanaburi' }, href: 'city-kanchanaburi.html', stayHref: 'where-to-stay-kanchanaburi.html',
      blurb: { th: 'สะพานข้ามแม่น้ำแคว น้ำตกเอราวัณ และแพริมน้ำ ขับรถจากกรุงเทพราว 2-2.5 ชั่วโมง ไปเช้า-เย็นกลับได้ แต่ค้างริมน้ำสัก 1 คืนจะคุ้มกว่า', en: 'The River Kwai bridge, Erawan waterfall and river rafts, about 2–2.5 hours from Bangkok — doable in a day, though an overnight by the river is more rewarding.' },
      tags: { th: ['น้ำตกเอราวัณ', 'สะพานแคว'], en: ['Erawan Falls', 'River Kwai'] } },
    { name: { th: 'อัมพวา (สมุทรสงคราม)', en: 'Amphawa (Samut Songkhram)' }, href: 'city-samut-songkhram.html', stayHref: 'where-to-stay-samut-songkhram.html',
      blurb: { th: 'ตลาดน้ำอัมพวายามเย็น นั่งเรือชมหิ่งห้อย และตลาดร่มหุบแม่กลอง ใกล้กรุงเทพราว 1.5 ชั่วโมง เหมาะไปเที่ยวบ่าย-เย็น', en: 'The evening Amphawa floating market, firefly boat trips and the Maeklong railway market, about 1.5 hours from Bangkok — great for an afternoon-into-evening trip.' },
      tags: { th: ['ตลาดน้ำ', 'ตลาดร่มหุบ'], en: ['Floating market', 'Railway market'] } },
    { name: { th: 'บางแสน (ชลบุรี)', en: 'Bang Saen (Chonburi)' }, href: 'city-chonburi.html', stayHref: 'where-to-stay-bang-saen.html',
      blurb: { th: 'หาดทะเลที่ใกล้กรุงเทพที่สุด ราว 1.5-2 ชั่วโมง เล่นน้ำ นั่งเก้าอี้ผ้าใบกินอาหารทะเลริมหาด เหมาะหนีกรุงไปทะเลแบบวันเดียว', en: 'The closest beach to Bangkok, about 1.5–2 hours away — swim, sit in a deck chair and eat seafood on the sand, perfect for a one-day seaside escape.' },
      tags: { th: ['ทะเลใกล้สุด', 'อาหารทะเล'], en: ['Nearest beach', 'Seafood'] } },
    { name: { th: 'เขาใหญ่', en: 'Khao Yai' }, href: 'city-khao-yai.html', stayHref: 'where-to-stay-khao-yai.html',
      blurb: { th: 'อุทยานแห่งชาติ น้ำตก สัตว์ป่า ไร่องุ่น และคาเฟ่วิวเขา ขับรถจากกรุงเทพราว 2.5-3 ชั่วโมง เที่ยวธรรมชาติแบบไม่ไกล', en: 'A national park with waterfalls and wildlife, plus vineyards and hill-view cafés, about 2.5–3 hours from Bangkok — nature without going far.' },
      tags: { th: ['อุทยาน-น้ำตก', 'ไร่องุ่น-คาเฟ่'], en: ['Park & waterfalls', 'Vineyards & cafés'] } },
    { name: { th: 'ราชบุรี', en: 'Ratchaburi' }, href: 'city-ratchaburi.html', stayHref: 'where-to-stay-ratchaburi.html',
      blurb: { th: 'ตลาดน้ำดำเนินสะดวก ถ้ำเขางู เครื่องปั้นโอ่งมังกร และคาเฟ่-ที่เที่ยวสวนผึ้ง ใกล้กรุงเทพราว 1.5-2 ชั่วโมง', en: 'The Damnoen Saduak floating market, cave temples, dragon-jar pottery and the Suan Phueng cafés and resorts, about 1.5–2 hours from Bangkok.' },
      tags: { th: ['ตลาดน้ำ', 'สวนผึ้ง'], en: ['Floating market', 'Suan Phueng'] } },
  ],
  faq: [
    { q: { th: 'เที่ยวใกล้กรุงเทพไม่มีรถไปไหนได้บ้าง?', en: 'Which day trips from Bangkok work without a car?' },
      a: { th: 'อยุธยานั่งรถไฟหรือรถตู้จากกรุงเทพได้สะดวกสุด อัมพวาและบางแสนมีรถตู้/รถทัวร์ไปลงใจกลาง ส่วนกาญจนบุรีก็มีรถไฟสายน้ำตก เขาใหญ่กับราชบุรีจะสะดวกกว่าถ้ามีรถหรือเช่ารถ เพราะที่เที่ยวกระจาย', en: 'Ayutthaya is easiest by train or minivan; Amphawa and Bang Saen have minivans and buses to the center; and Kanchanaburi has the scenic train line. Khao Yai and Ratchaburi are easier with a car or rental, as the sights are spread out.' } },
    { q: { th: 'ที่ไหนเหมาะไปเช้า-เย็นกลับจริง ๆ?', en: 'Which are truly fine as a single day out-and-back?' },
      a: { th: 'อยุธยา อัมพวา บางแสน และราชบุรี (ดำเนินสะดวก) ไปเช้า-เย็นกลับสบายเพราะใกล้และเที่ยวจุดหลักได้ในวันเดียว ส่วนกาญจนบุรีและเขาใหญ่ไปเช้า-เย็นกลับได้แต่ค้าง 1 คืนจะเที่ยวได้เต็มกว่า', en: 'Ayutthaya, Amphawa, Bang Saen and Ratchaburi (Damnoen Saduak) are comfortable out-and-back as they are close and the main sights fit one day, while Kanchanaburi and Khao Yai work too but one overnight lets you see more.' } },
    { q: { th: 'อยากไปทะเลใกล้กรุงเทพไปไหน?', en: 'Where is the nearest beach trip from Bangkok?' },
      a: { th: 'บางแสน (ชลบุรี) ใกล้สุด ขับรถราว 1.5-2 ชั่วโมง ถ้าอยากได้เกาะเลือกเกาะเสม็ด (ระยอง) ที่ต้องต่อเรือสั้น ๆ เหมาะค้าง 1 คืน ส่วนพัทยาก็ใกล้และมีครบทั้งหาดและไนต์ไลฟ์', en: 'Bang Saen (Chonburi) is closest, about 1.5–2 hours by car; for an island, Koh Samet (Rayong) needs a short ferry and is best with an overnight; and Pattaya is also close, with both beach and nightlife.' } },
  ],
},
{ slug: 'best-temple-destinations-thailand', hero: 'nakhon-phanom', emoji: '🛕',
  th: { eyebrow: 'วัด & สายมู', h1: 'สายวัด-สายมู<br>ไปจังหวัดไหนดี', title: 'เที่ยววัด-สายมูที่ไหนดีในไทย 2026 — 6 จังหวัดวัดสวย พระธาตุศักดิ์สิทธิ์ | ThailandAddict',
    metaDesc: 'สายวัด-สายมูอยากกราบพระ ขอพร เที่ยววัดสวยไปไหนดี? รวม 6 จังหวัด อยุธยา สุโขทัย เชียงใหม่ น่าน นครพนม นครศรีธรรมราช พร้อมที่พัก',
    intro: 'รวมจังหวัดที่วัดสวยและพระธาตุศักดิ์สิทธิ์ เหมาะสายวัด-สายมูและคนชอบสถาปัตยกรรมโบราณ พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายโบราณสถานเลือก <strong>อยุธยา</strong> และ <strong>สุโขทัย</strong> สายวัดล้านนาเลือก <strong>เชียงใหม่</strong> (ดอยสุเทพ) หรือ <strong>น่าน</strong> (วัดภูมินทร์) สายพระธาตุศักดิ์สิทธิ์เลือก <strong>นครพนม</strong> (พระธาตุพนม) และ <strong>นครศรีธรรมราช</strong> (วัดพระมหาธาตุ)' },
  en: { eyebrow: 'Temples & merit', h1: 'Best temple<br>destinations', title: 'Best Temple Destinations in Thailand 2026 — 6 Sacred Picks | ThailandAddict',
    metaDesc: 'Where to go for temples and sacred sites in Thailand? Six picks — Ayutthaya, Sukhothai, Chiang Mai, Nan, Nakhon Phanom and Nakhon Si Thammarat — with where to stay.',
    intro: 'Provinces with beautiful temples and revered stupas, ideal for temple-lovers and fans of ancient architecture, each with where to stay.',
    quick: '<strong>Short answer:</strong> For ancient ruins choose <strong>Ayutthaya</strong> and <strong>Sukhothai</strong>; for Lanna temples, <strong>Chiang Mai</strong> (Doi Suthep) or <strong>Nan</strong> (Wat Phumin); for revered stupas, <strong>Nakhon Phanom</strong> (Phra That Phanom) and <strong>Nakhon Si Thammarat</strong> (Wat Phra Mahathat).' },
  items: [
    { name: { th: 'อยุธยา', en: 'Ayutthaya' }, href: 'city-ayutthaya.html', stayHref: 'where-to-stay-ayutthaya.html',
      blurb: { th: 'เมืองมรดกโลก เต็มไปด้วยวัดและเจดีย์เก่าแก่ ไฮไลต์คือเศียรพระในรากไม้ที่วัดมหาธาตุ และวัดไชยวัฒนาราม ริมแม่น้ำยามเย็น', en: 'A World Heritage city full of old temples and stupas — highlights include the Buddha head in the tree roots at Wat Mahathat and riverside Wat Chaiwatthanaram at dusk.' },
      tags: { th: ['มรดกโลก', 'เศียรพระในรากไม้'], en: ['World Heritage', 'Buddha in tree roots'] } },
    { name: { th: 'สุโขทัย', en: 'Sukhothai' }, href: 'city-sukhothai.html', stayHref: 'where-to-stay-sukhothai.html',
      blurb: { th: 'อุทยานประวัติศาสตร์ราชธานีแรกของไทย วัดมหาธาตุ วัดศรีชุมพระพักตร์ใหญ่ ปั่นจักรยานชมโบราณสถานท่ามกลางสระน้ำได้ทั้งวัน', en: 'The historical park of Thailand’s first capital — Wat Mahathat and the giant Buddha face at Wat Si Chum, with a full day of cycling among ruins and lotus ponds.' },
      tags: { th: ['อุทยานประวัติศาสตร์', 'ปั่นจักรยาน'], en: ['Historical park', 'Cycling'] } },
    { name: { th: 'เชียงใหม่', en: 'Chiang Mai' }, href: 'city-chiang-mai.html', stayHref: 'where-to-stay-chiang-mai.html',
      blurb: { th: 'วัดล้านนาในคูเมืองและวัดพระธาตุดอยสุเทพบนยอดเขา วิวเมืองสวย เป็นวัดคู่บ้านคู่เมืองที่คนมาเชียงใหม่ต้องขึ้นไปไหว้', en: 'Lanna temples inside the old moat plus Wat Phra That Doi Suthep on its hilltop with city views — the signature temple every Chiang Mai visitor climbs up to.' },
      tags: { th: ['ดอยสุเทพ', 'วัดล้านนา'], en: ['Doi Suthep', 'Lanna temples'] } },
    { name: { th: 'น่าน', en: 'Nan' }, href: 'city-nan.html', stayHref: 'where-to-stay-nan.html',
      blurb: { th: 'วัดภูมินทร์กับจิตรกรรม “ปู่ม่านย่าม่าน” (กระซิบรัก) และวัดเก่าเมืองน่านที่เงียบสงบ บรรยากาศเมืองเล็กน่าเดินไหว้พระ', en: 'Wat Phumin with its “whispering lovers” mural and the quiet old temples of Nan town — a small-town setting that is lovely for a temple stroll.' },
      tags: { th: ['วัดภูมินทร์', 'จิตรกรรมกระซิบรัก'], en: ['Wat Phumin', 'Whispering mural'] } },
    { name: { th: 'นครพนม', en: 'Nakhon Phanom' }, href: 'city-nakhon-phanom.html', stayHref: 'where-to-stay-nakhon-phanom.html',
      blurb: { th: 'พระธาตุพนม พระธาตุศักดิ์สิทธิ์คู่ลุ่มน้ำโขงและคนอีสาน เมืองริมโขงเงียบสงบ วิวฝั่งลาว เหมาะสายมูที่อยากกราบพระธาตุประจำปีเกิด', en: 'Phra That Phanom, a sacred stupa central to the Mekong and Isan people, in a quiet riverside town with Laos across the water — a key pilgrimage for merit-makers.' },
      tags: { th: ['พระธาตุพนม', 'ริมโขง'], en: ['Phra That Phanom', 'Mekong town'] } },
    { name: { th: 'นครศรีธรรมราช', en: 'Nakhon Si Thammarat' }, href: 'city-nakhon-si-thammarat.html', stayHref: 'where-to-stay-nakhon-si-thammarat.html',
      blurb: { th: 'วัดพระมหาธาตุวรมหาวิหาร เจดีย์ทองคู่บ้านคู่เมืองภาคใต้ ไหว้พระเสริมสิริมงคล มีไอ้ไข่วัดเจดีย์ที่สายมูนิยมไปขอพรด้วย', en: 'Wat Phra Mahathat, the South’s great golden stupa, plus the Ai Khai shrine at Wat Chedi that draws merit-seekers hoping for good fortune.' },
      tags: { th: ['วัดพระมหาธาตุ', 'ไอ้ไข่'], en: ['Wat Phra Mahathat', 'Ai Khai shrine'] } },
  ],
  faq: [
    { q: { th: 'เที่ยววัดจังหวัดไหนเหมาะสายมูที่สุด?', en: 'Which province is best for merit-making?' },
      a: { th: 'นครพนม (พระธาตุพนม) และนครศรีธรรมราช (วัดพระมหาธาตุ + ไอ้ไข่) เป็นหมุดหมายสายมูยอดนิยม คนนิยมไปไหว้พระธาตุประจำปีเกิดและขอพร ส่วนเชียงใหม่ (ดอยสุเทพ) ก็เป็นวัดศักดิ์สิทธิ์ที่คนไทยและต่างชาติไปกราบเยอะ', en: 'Nakhon Phanom (Phra That Phanom) and Nakhon Si Thammarat (Wat Phra Mahathat and the Ai Khai shrine) are favorites for merit-making and birth-year stupa pilgrimages, while Chiang Mai’s Doi Suthep is a sacred temple visited by Thais and foreigners alike.' } },
    { q: { th: 'เที่ยวโบราณสถานเลือกอยุธยาหรือสุโขทัย?', en: 'Ayutthaya or Sukhothai for ancient ruins?' },
      a: { th: 'อยุธยาใกล้กรุงเทพ ไปเช้า-เย็นกลับได้ โบราณสถานใหญ่และอยู่กระจายในเมือง ส่วนสุโขทัยไกลกว่าแต่อุทยานเป็นระเบียบสวยงาม ปั่นจักรยานชมได้สบาย บรรยากาศสงบกว่า เลือกตามเวลาที่มีและความสะดวกในการเดินทาง', en: 'Ayutthaya is near Bangkok and doable as a day trip, with large ruins spread across town, while Sukhothai is farther but has a tidy, scenic park that is easy to cycle and feels calmer — choose by your time and how far you want to travel.' } },
    { q: { th: 'แต่งตัวไปวัดต้องระวังอะไร?', en: 'What should I wear to temples?' },
      a: { th: 'ควรแต่งตัวสุภาพ ปิดไหล่และเข่า ทั้งชายและหญิง บางวัดมีผ้าให้ยืมคลุม ถอดรองเท้าก่อนเข้าโบสถ์/วิหาร และสำรวมเสียง ไม่ชี้เท้าไปทางพระพุทธรูป จะช่วยให้เที่ยววัดได้อย่างเหมาะสม', en: 'Dress modestly with shoulders and knees covered, for both men and women; some temples lend cover-ups. Remove your shoes before entering the ordination or assembly hall, keep your voice down and do not point your feet at Buddha images.' } },
  ],
},
{ slug: 'best-cafe-hopping-thailand', hero: 'nan', emoji: '☕',
  th: { eyebrow: 'คาเฟ่ & ของหวาน', h1: 'สายคาเฟ่<br>ไปเที่ยวไหนดี', title: 'สายคาเฟ่เที่ยวไหนดีในไทย 2026 — 6 เมืองคาเฟ่เด็ด นั่งชิลถ่ายรูป | ThailandAddict',
    metaDesc: 'สายคาเฟ่อยากเที่ยวเมืองคาเฟ่เยอะ ๆ นั่งชิลถ่ายรูปไปไหนดี? รวม 6 เมือง เชียงใหม่ น่าน เขาค้อ เชียงราย หัวหิน กรุงเทพ พร้อมที่พัก',
    intro: 'รวมเมืองที่คาเฟ่เยอะและบรรยากาศดี ตั้งแต่คาเฟ่วิวเขาถึงคาเฟ่ในตึกเก่า เหมาะสายนั่งชิลถ่ายรูป พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายคาเฟ่ฮิปเลือก <strong>เชียงใหม่</strong> (นิมมาน) สายคาเฟ่วิวเขา-วิวนาเลือก <strong>น่าน</strong> หรือ <strong>เขาค้อ (เพชรบูรณ์)</strong> สายไร่ชา-วิวดอยเลือก <strong>เชียงราย</strong> สายคาเฟ่ริมทะเลเลือก <strong>หัวหิน</strong> ส่วนสายคาเฟ่ในเมืองเลือก <strong>กรุงเทพ</strong> (อารีย์/ทองหล่อ)' },
  en: { eyebrow: 'Cafés & sweets', h1: 'Best places for<br>café-hopping', title: 'Best Café-Hopping Destinations in Thailand 2026 — 6 Picks | ThailandAddict',
    metaDesc: 'Where to go café-hopping in Thailand? Six picks — Chiang Mai, Nan, Khao Kho, Chiang Rai, Hua Hin and Bangkok — with where to stay.',
    intro: 'Towns with lots of cafés and good atmosphere, from hill-view spots to old-shophouse coffee, ideal for slow days and photos, each with where to stay.',
    quick: '<strong>Short answer:</strong> For hip cafés choose <strong>Chiang Mai</strong> (Nimman); for hill and field views, <strong>Nan</strong> or <strong>Khao Kho (Phetchabun)</strong>; for tea plantations and mountain views, <strong>Chiang Rai</strong>; for seaside cafés, <strong>Hua Hin</strong>; and for city cafés, <strong>Bangkok</strong> (Ari/Thong Lo).' },
  items: [
    { name: { th: 'เชียงใหม่ (นิมมาน)', en: 'Chiang Mai (Nimman)' }, href: 'city-chiang-mai.html', stayHref: 'where-to-stay-chiang-mai.html',
      blurb: { th: 'เมืองคาเฟ่อันดับต้นของไทย ย่านนิมมานมีคาเฟ่ฮิปและโรงคั่วกาแฟเยอะมาก รอบเมืองยังมีคาเฟ่วิวดอยและวิวนาให้นั่งชิลทั้งวัน', en: 'One of Thailand’s top café cities — Nimman is packed with hip cafés and roasters, and around town there are mountain- and field-view spots to linger all day.' },
      tags: { th: ['นิมมาน', 'โรงคั่วกาแฟ'], en: ['Nimman', 'Coffee roasters'] } },
    { name: { th: 'น่าน', en: 'Nan' }, href: 'city-nan.html', stayHref: 'where-to-stay-nan.html',
      blurb: { th: 'เมืองเล็กเงียบ ๆ มีคาเฟ่วิวนาขั้นบันไดที่ปัวและคาเฟ่ในเมืองเก่าน่ารัก ๆ บรรยากาศช้า ๆ เหมาะนั่งจิบกาแฟชมวิวภูเขา', en: 'A quiet small town with rice-terrace cafés around Pua and cute old-town spots — a slow pace ideal for sipping coffee with mountain views.' },
      tags: { th: ['คาเฟ่วิวนา', 'เมืองเล็กเงียบ'], en: ['Field-view cafés', 'Quiet town'] } },
    { name: { th: 'เขาค้อ (เพชรบูรณ์)', en: 'Khao Kho (Phetchabun)' }, href: 'city-phetchabun.html', stayHref: 'where-to-stay-phetchabun.html',
      blurb: { th: 'ภูเขาใกล้กรุงเทพที่คาเฟ่วิวทะเลหมอกเยอะมาก ขับรถขึ้นเขาแวะคาเฟ่วิวภูเขาได้เป็นสิบร้าน เหมาะสายถ่ายรูปช่วงเช้าหมอกลง', en: 'A mountain area near Bangkok with many sea-of-mist cafés — drive up and stop at a dozen hill-view spots, great for misty-morning photos.' },
      tags: { th: ['คาเฟ่วิวหมอก', 'ใกล้กรุงเทพ'], en: ['Misty-view cafés', 'Near Bangkok'] } },
    { name: { th: 'เชียงราย', en: 'Chiang Rai' }, href: 'city-chiang-rai.html', stayHref: 'where-to-stay-chiang-rai.html',
      blurb: { th: 'เหนือสุดที่มีคาเฟ่ไร่ชา (ไร่ชาฉุยฟง) และคาเฟ่วิวดอยสวย ๆ รอบเมือง ผสมกับวัดสีขาว-สีน้ำเงิน เที่ยวคาเฟ่ควบวัดได้ในทริปเดียว', en: 'The far north has tea-plantation cafés (like Choui Fong) and pretty mountain-view spots, paired with the White and Blue temples — combine cafés and temples in one trip.' },
      tags: { th: ['คาเฟ่ไร่ชา', 'วิวดอย'], en: ['Tea-farm cafés', 'Mountain views'] } },
    { name: { th: 'หัวหิน', en: 'Hua Hin' }, href: 'city-huahin.html', stayHref: 'where-to-stay-huahin.html',
      blurb: { th: 'เมืองทะเลใกล้กรุงเทพที่มีคาเฟ่ริมทะเลและคาเฟ่สไตล์สวนสวย ๆ เยอะ รวมถึงตลาดซิเคด้าและร้านนั่งชิลริมหาด เที่ยวคาเฟ่ควบทะเลได้', en: 'A seaside town near Bangkok with plenty of beachfront and garden-style cafés, plus the Cicada Market and shore-side spots — café-hop with the sea right there.' },
      tags: { th: ['คาเฟ่ริมทะเล', 'ใกล้กรุงเทพ'], en: ['Seaside cafés', 'Near Bangkok'] } },
    { name: { th: 'กรุงเทพ (อารีย์/ทองหล่อ)', en: 'Bangkok (Ari/Thong Lo)' }, href: 'city-bangkok.html', stayHref: 'where-to-stay-bangkok.html',
      blurb: { th: 'ย่านอารีย์ ทองหล่อ และเอกมัยเต็มไปด้วยคาเฟ่สเปเชียลตี้และคาเฟ่ดีไซน์สวย เดินทางด้วย BTS สะดวก เหมาะสายคาเฟ่ในเมืองที่ไม่อยากไปไกล', en: 'Ari, Thong Lo and Ekkamai are full of specialty and design-led cafés, easy to reach by BTS — ideal for city café-hopping without leaving town.' },
      tags: { th: ['สเปเชียลตี้', 'ติด BTS'], en: ['Specialty coffee', 'On the BTS'] } },
  ],
  faq: [
    { q: { th: 'เมืองไหนคาเฟ่เยอะที่สุดในไทย?', en: 'Which Thai city has the most cafés?' },
      a: { th: 'เชียงใหม่ขึ้นชื่อว่าคาเฟ่เยอะและหลากหลายที่สุด ตั้งแต่นิมมานสายฮิปถึงคาเฟ่วิวดอยรอบเมือง ส่วนกรุงเทพก็มีคาเฟ่สเปเชียลตี้เยอะย่านอารีย์-ทองหล่อ เลือกตามว่าอยากได้บรรยากาศเมืองหรือวิวธรรมชาติ', en: 'Chiang Mai is known for the most and most varied cafés, from hip Nimman to mountain-view spots around town, while Bangkok has many specialty cafés in Ari and Thong Lo — choose by whether you want a city vibe or nature views.' } },
    { q: { th: 'สายคาเฟ่วิวภูเขาไปไหนดี?', en: 'Where for mountain-view cafés?' },
      a: { th: 'เขาค้อ (เพชรบูรณ์) ใกล้กรุงเทพสุดและคาเฟ่วิวทะเลหมอกเยอะ ส่วนน่านและเชียงรายมีคาเฟ่วิวนาขั้นบันไดและไร่ชาสวย ๆ ช่วงเช้าหน้าหนาวหมอกลงสวยที่สุด ควรไปแต่เช้าเพื่อเจอวิวดี ๆ', en: 'Khao Kho (Phetchabun) is closest to Bangkok with many sea-of-mist cafés, while Nan and Chiang Rai have lovely rice-terrace and tea-farm views; misty cool-season mornings are best, so go early for the good views.' } },
    { q: { th: 'เที่ยวคาเฟ่ควบที่เที่ยวอื่นได้ไหม?', en: 'Can I combine café-hopping with other sights?' },
      a: { th: 'ได้สบาย เชียงใหม่และเชียงรายเที่ยวคาเฟ่ควบวัดและธรรมชาติได้ หัวหินควบทะเลและตลาด ส่วนน่านควบเมืองเก่าและวัด คาเฟ่ส่วนใหญ่อยู่ใกล้แหล่งเที่ยวอยู่แล้ว วางแผนแวะระหว่างทางได้ลงตัว', en: 'Easily — Chiang Mai and Chiang Rai mix cafés with temples and nature, Hua Hin with the beach and markets, and Nan with the old town and temples; most cafés sit near the sights, so it is easy to stop along the way.' } },
  ],
},
{ slug: 'best-waterfalls-nature-thailand', hero: 'kanchanaburi', emoji: '💦',
  th: { eyebrow: 'น้ำตก & ธรรมชาติ', h1: 'น้ำตก-ธรรมชาติ<br>ไปที่ไหนดี', title: 'เที่ยวน้ำตก-ธรรมชาติที่ไหนดีในไทย 2026 — 6 ที่น้ำตกสวย ป่าเขียว | ThailandAddict',
    metaDesc: 'อยากเที่ยวน้ำตกสวย ๆ ป่าเขียว ๆ ในไทยไปไหนดี? รวม 6 ที่ กาญจนบุรี เขาใหญ่ ตาก(ทีลอซู) เลย เพชรบูรณ์ จันทบุรี พร้อมที่พัก',
    intro: 'รวมจุดหมายน้ำตกและธรรมชาติที่สวยสุดในไทย เลือกตามภาคและความง่ายในการเข้าถึง พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> น้ำตกสวยเข้าง่ายเลือก <strong>กาญจนบุรี</strong> (เอราวัณ) หรือ <strong>เขาใหญ่</strong> (เหวสุวัต) สายน้ำตกใหญ่ที่สุดเลือก <strong>ตาก</strong> (ทีลอซู/อุ้มผาง) สายภูเขา-น้ำตกอีสานเลือก <strong>เลย</strong> (ภูกระดึง) หรือ <strong>เพชรบูรณ์</strong> (เขาค้อ) ส่วนสายน้ำตกภาคตะวันออกเลือก <strong>จันทบุรี</strong> (น้ำตกพลิ้ว)' },
  en: { eyebrow: 'Waterfalls & nature', h1: 'Best waterfalls<br>& nature', title: 'Best Waterfalls & Nature Trips in Thailand 2026 — 6 Picks | ThailandAddict',
    metaDesc: 'Where to see waterfalls and green nature in Thailand? Six picks — Kanchanaburi, Khao Yai, Tak (Thi Lo Su), Loei, Phetchabun and Chanthaburi — with where to stay.',
    intro: 'The best waterfall and nature destinations in Thailand, sorted by region and how easy they are to reach, each with where to stay.',
    quick: '<strong>Short answer:</strong> For lovely, easy-access falls choose <strong>Kanchanaburi</strong> (Erawan) or <strong>Khao Yai</strong> (Haew Suwat); for the biggest waterfall, <strong>Tak</strong> (Thi Lo Su/Umphang); for Isan mountains and falls, <strong>Loei</strong> (Phu Kradueng) or <strong>Phetchabun</strong> (Khao Kho); and for the east, <strong>Chanthaburi</strong> (Phlio waterfall).' },
  items: [
    { name: { th: 'กาญจนบุรี (เอราวัณ)', en: 'Kanchanaburi (Erawan)' }, href: 'city-kanchanaburi.html', stayHref: 'where-to-stay-kanchanaburi.html',
      blurb: { th: 'น้ำตกเอราวัณ 7 ชั้นน้ำเขียวมรกตขึ้นชื่อที่สุดของไทย เดินขึ้นชั้นบนได้ มีแม่น้ำ แพริมน้ำ และป่าเขียว เหมาะเที่ยวธรรมชาติใกล้กรุงเทพ', en: 'The seven-tier Erawan waterfall with its famous emerald pools is one of Thailand’s best — hike to the upper tiers, with the river, raft stays and green forest, all near Bangkok.' },
      tags: { th: ['เอราวัณ 7 ชั้น', 'น้ำเขียวมรกต'], en: ['Seven-tier falls', 'Emerald pools'] } },
    { name: { th: 'เขาใหญ่', en: 'Khao Yai' }, href: 'city-khao-yai.html', stayHref: 'where-to-stay-khao-yai.html',
      blurb: { th: 'อุทยานแห่งชาติแห่งแรกของไทย น้ำตกเหวสุวัต-เหวนรก ป่าใหญ่ สัตว์ป่า และเส้นทางเดินป่า หน้าฝนน้ำตกเต็มและเขียวสวยสุด', en: 'Thailand’s first national park, with the Haew Suwat and Haew Narok waterfalls, big forest, wildlife and trails — falls are full and the green is best in the rains.' },
      tags: { th: ['เหวสุวัต', 'เดินป่า-สัตว์ป่า'], en: ['Haew Suwat', 'Trails & wildlife'] } },
    { name: { th: 'ตาก (ทีลอซู/อุ้มผาง)', en: 'Tak (Thi Lo Su/Umphang)' }, href: 'city-tak.html', stayHref: 'where-to-stay-tak.html',
      blurb: { th: 'น้ำตกทีลอซูที่ใหญ่ที่สุดในไทย กว้างและสูงตระการตา อยู่ในอุ้มผาง ต้องนั่งรถและล่องแก่งเข้าไป เหมาะสายผจญภัยที่อยากเห็นน้ำตกระดับท็อป', en: 'Thi Lo Su, Thailand’s largest waterfall — wide and tall — sits in Umphang and is reached by road and rafting, ideal for adventurers who want a top-tier falls.' },
      tags: { th: ['น้ำตกใหญ่สุด', 'ล่องแก่ง'], en: ['Largest falls', 'White-water rafting'] } },
    { name: { th: 'เลย', en: 'Loei' }, href: 'city-loei.html', stayHref: 'where-to-stay-loei.html',
      blurb: { th: 'ภูเขาอีสานบน ภูกระดึงและภูเรือ น้ำตก ป่าสน และอากาศเย็น เหมาะสายเดินป่า-แค้มป์ หน้าฝนเขียวสวยและน้ำตกเต็ม คนน้อยกว่าหน้าหนาว', en: 'The upper-Isan mountains — Phu Kradueng and Phu Ruea, with waterfalls, pine forest and cool air, great for hiking and camping; lush and full in the rains, quieter than in winter.' },
      tags: { th: ['ภูกระดึง', 'เดินป่า-แค้มป์'], en: ['Phu Kradueng', 'Hiking & camping'] } },
    { name: { th: 'เพชรบูรณ์ (เขาค้อ)', en: 'Phetchabun (Khao Kho)' }, href: 'city-phetchabun.html', stayHref: 'where-to-stay-phetchabun.html',
      blurb: { th: 'เขาค้อและภูทับเบิก ทะเลหมอก น้ำตก และวิวภูเขาเป็นชั้น ๆ ใกล้กรุงเทพสุดในบรรดาภูเขาทะเลหมอก เหมาะขับรถเที่ยวธรรมชาติสุดสัปดาห์', en: 'Khao Kho and Phu Thap Boek, with the sea of mist, waterfalls and layered mountain views — the closest misty mountains to Bangkok, great for a weekend nature drive.' },
      tags: { th: ['ทะเลหมอก', 'วิวภูเขา'], en: ['Sea of mist', 'Mountain views'] } },
    { name: { th: 'จันทบุรี (น้ำตกพลิ้ว)', en: 'Chanthaburi (Phlio Falls)' }, href: 'city-chanthaburi.html', stayHref: 'where-to-stay-chanthaburi.html',
      blurb: { th: 'น้ำตกพลิ้วที่มีฝูงปลาในลำธารใส และเขาคิชฌกูฏ (รอยพระพุทธบาทบนยอดเขา ช่วงเปิดฤดูแสวงบุญ) เมืองริมน้ำเงียบ ๆ เหมาะสายธรรมชาติภาคตะวันออก', en: 'Phlio waterfall with its fish-filled clear stream and Khao Khitchakut (a hilltop Buddha footprint open in pilgrimage season), in a quiet riverside province — great east-coast nature.' },
      tags: { th: ['น้ำตกพลิ้ว', 'เขาคิชฌกูฏ'], en: ['Phlio Falls', 'Khao Khitchakut'] } },
  ],
  faq: [
    { q: { th: 'น้ำตกไปหน้าไหนสวยสุด?', en: 'What season are waterfalls best?' },
      a: { th: 'น้ำตกเต็มและสวยสุดช่วงหน้าฝน-ปลายฝน (มิ.ย.-พ.ย.) เพราะน้ำเยอะและป่าเขียว แต่ทางอาจลื่นและบางจุด (เช่น อุ้มผาง) เข้าได้เฉพาะบางช่วง ควรเช็กสภาพเส้นทางก่อนไปและระวังกระแสน้ำแรง', en: 'Waterfalls are fullest and best in and just after the rains (Jun–Nov), with lots of water and green forest, but paths can be slippery and some spots (like Umphang) are only accessible in certain months — check trail conditions first and watch for strong currents.' } },
    { q: { th: 'น้ำตกที่ใหญ่ที่สุดในไทยอยู่ที่ไหน?', en: 'Where is Thailand’s biggest waterfall?' },
      a: { th: 'น้ำตกทีลอซู ในอุ้มผาง จังหวัดตาก เป็นน้ำตกที่ใหญ่ที่สุดในไทย กว้างและสูงเป็นม่านน้ำขนาดใหญ่ การเข้าถึงต้องนั่งรถและบางช่วงล่องแก่ง เหมาะวางแผนค้างในอุ้มผาง 1-2 คืน', en: 'Thi Lo Su in Umphang, Tak Province, is Thailand’s largest waterfall — a wide, tall curtain of water reached by road and, in places, rafting, so plan one or two nights in Umphang.' } },
    { q: { th: 'เที่ยวน้ำตกใกล้กรุงเทพไปไหนดี?', en: 'Which waterfalls are nearest Bangkok?' },
      a: { th: 'กาญจนบุรี (เอราวัณ) และเขาใหญ่ (เหวสุวัต) ใกล้กรุงเทพสุด ขับรถ 2-3 ชั่วโมง น้ำตกสวยและเข้าถึงง่าย เหมาะไปเช้า-เย็นกลับหรือค้าง 1 คืน ส่วนเขาค้อ (เพชรบูรณ์) ก็ไม่ไกลและได้ทั้งน้ำตกและทะเลหมอก', en: 'Kanchanaburi (Erawan) and Khao Yai (Haew Suwat) are closest, a 2–3 hour drive, with pretty, easy-access falls good for a day trip or overnight, while Khao Kho (Phetchabun) is also not far and offers both waterfalls and the sea of mist.' } },
  ],
},
{ slug: 'best-budget-backpacker-thailand', hero: 'chiang-rai', emoji: '🎒',
  th: { eyebrow: 'แบ็คแพ็ค & งบน้อย', h1: 'แบ็คแพ็คงบน้อย<br>ไปเที่ยวไหนดี', title: 'แบ็คแพ็คงบน้อยเที่ยวไหนดีในไทย 2026 — 5 ที่ของถูก เที่ยวคุ้ม | ThailandAddict',
    metaDesc: 'งบน้อยอยากแบ็คแพ็คเที่ยวไทยไปไหนดี? รวม 5 ที่ของถูก ที่พักเบา ๆ ปาย เชียงใหม่ เชียงราย เกาะพะงัน กาญจนบุรี พร้อมที่พัก',
    intro: 'รวมจุดหมายที่ของกิน-ที่พักราคาเบา เที่ยวสนุกแบบงบน้อย เหมาะสายแบ็คแพ็คและนักเรียนนักศึกษา พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายภูเขา-เมืองชิลเลือก <strong>ปาย</strong> หรือ <strong>เชียงใหม่</strong> (เกสต์เฮาส์-คาเฟ่ถูก) สายเหนือสุด-วัดสวยเลือก <strong>เชียงราย</strong> สายเกาะ-บังกะโลริมหาดเลือก <strong>เกาะพะงัน</strong> ส่วนสายธรรมชาติใกล้กรุงเทพเลือก <strong>กาญจนบุรี</strong> (แพริมน้ำราคาเบา)' },
  en: { eyebrow: 'Budget & backpacking', h1: 'Best budget<br>backpacker trips', title: 'Best Budget Backpacker Destinations in Thailand 2026 — 5 Picks | ThailandAddict',
    metaDesc: 'Where to backpack Thailand on a budget? Five picks — Pai, Chiang Mai, Chiang Rai, Koh Phangan and Kanchanaburi — with cheap stays and where to stay.',
    intro: 'Destinations with cheap food and stays where you can have a great time on a small budget, ideal for backpackers and students, each with where to stay.',
    quick: '<strong>Short answer:</strong> For mountains and laid-back towns choose <strong>Pai</strong> or <strong>Chiang Mai</strong> (cheap guesthouses and cafés); for the far north and temples, <strong>Chiang Rai</strong>; for islands and beach bungalows, <strong>Koh Phangan</strong>; and for nature near Bangkok, <strong>Kanchanaburi</strong> (affordable river rafts).' },
  items: [
    { name: { th: 'ปาย (แม่ฮ่องสอน)', en: 'Pai (Mae Hong Son)' }, href: 'city-pai.html', stayHref: 'where-to-stay-pai.html',
      blurb: { th: 'เมืองเล็กในหุบเขา เกสต์เฮาส์และบังกะโลราคาเบา ถนนคนเดิน คาเฟ่ และคนเที่ยวเป็นมิตร เป็นเมืองแบ็คแพ็คคลาสสิกของภาคเหนือ', en: 'A small mountain town with cheap guesthouses and bungalows, a walking street, cafés and a friendly traveler crowd — a classic northern backpacker stop.' },
      tags: { th: ['เกสต์เฮาส์ถูก', 'เมืองแบ็คแพ็ค'], en: ['Cheap guesthouses', 'Backpacker town'] } },
    { name: { th: 'เชียงใหม่', en: 'Chiang Mai' }, href: 'city-chiang-mai.html', stayHref: 'where-to-stay-chiang-mai.html',
      blurb: { th: 'ฐานแบ็คแพ็คยอดนิยมของไทย ที่พักและอาหารถูก วัดเดินฟรี คาเฟ่ราคาเบา และทัวร์ดอย-น้ำตกหลายราคา อยู่ยาวได้สบายแบบงบน้อย', en: 'Thailand’s favorite backpacker base — cheap stays and food, free temple-walking, affordable cafés and a range of mountain and waterfall tours, easy for a long, low-budget stay.' },
      tags: { th: ['ที่พัก-อาหารถูก', 'อยู่ยาวคุ้ม'], en: ['Cheap stays & food', 'Good for long stays'] } },
    { name: { th: 'เชียงราย', en: 'Chiang Rai' }, href: 'city-chiang-rai.html', stayHref: 'where-to-stay-chiang-rai.html',
      blurb: { th: 'เหนือสุด ที่พักและตลาดราคาเบา วัดร่องขุ่น-วัดร่องเสือเต้นเที่ยวได้ถูก และต่อรถไปดอยหรือสามเหลี่ยมทองคำได้ เหมาะสายงบน้อยที่ชอบวัฒนธรรม', en: 'The far north with cheap stays and markets, low-cost visits to the White and Blue temples, and onward transport to the mountains or the Golden Triangle — good for budget travelers who like culture.' },
      tags: { th: ['ราคาเบา', 'วัดสวย'], en: ['Low prices', 'Beautiful temples'] } },
    { name: { th: 'เกาะพะงัน', en: 'Koh Phangan' }, href: 'city-koh-phangan.html', stayHref: 'where-to-stay-koh-phangan.html',
      blurb: { th: 'เกาะสายปาร์ตี้ที่ยังมีบังกะโลริมหาดราคาเบาโดยเฉพาะนอกคืนฟูลมูน หาดเงียบทางเหนือเหมาะอยู่ยาว เหมาะแบ็คแพ็คสายทะเลที่งบไม่สูง', en: 'A party island that still has cheap beach bungalows, especially outside Full Moon nights, with quiet northern beaches good for a long stay — great for budget beach backpackers.' },
      tags: { th: ['บังกะโลริมหาด', 'ฟูลมูน'], en: ['Beach bungalows', 'Full Moon'] } },
    { name: { th: 'กาญจนบุรี', en: 'Kanchanaburi' }, href: 'city-kanchanaburi.html', stayHref: 'where-to-stay-kanchanaburi.html',
      blurb: { th: 'ใกล้กรุงเทพ มีแพริมน้ำและเกสต์เฮาส์ราคาเบา น้ำตกเอราวัณ ประวัติศาสตร์สงคราม และธรรมชาติ เที่ยวคุ้มแบบไม่ต้องบินไปไกล', en: 'Near Bangkok, with affordable river rafts and guesthouses, the Erawan waterfall, wartime history and nature — great value without flying anywhere.' },
      tags: { th: ['แพริมน้ำถูก', 'ใกล้กรุงเทพ'], en: ['Cheap river rafts', 'Near Bangkok'] } },
  ],
  faq: [
    { q: { th: 'เที่ยวไทยงบวันละเท่าไหร่สำหรับแบ็คแพ็ค?', en: 'What daily budget for backpacking Thailand?' },
      a: { th: 'สายประหยัดจริง ๆ อยู่ได้ราววันละ 800-1,200 บาท (ดอร์ม/เกสต์เฮาส์ + อาหารตามสั่ง + รถสาธารณะ) เมืองเหนืออย่างปายและเชียงใหม่ถูกกว่าเกาะ ส่วนเกาะค่าที่พักและเรือจะดันงบขึ้น ควรเผื่อค่าทัวร์-เช่ามอเตอร์ไซค์ด้วย', en: 'A tight budget runs about 800–1,200 baht a day (dorm/guesthouse, local food and public transport); northern towns like Pai and Chiang Mai are cheaper than the islands, where rooms and boats push costs up, so budget extra for tours and motorbike rental.' } },
    { q: { th: 'แบ็คแพ็คภาคไหนถูกสุด?', en: 'Which region is cheapest for backpacking?' },
      a: { th: 'ภาคเหนือ (เชียงใหม่ ปาย เชียงราย) และอีสานถูกที่สุด ทั้งที่พัก อาหาร และการเดินทาง ส่วนเกาะทางใต้แพงกว่าเพราะต้องนั่งเรือและของกินนำเข้า ถ้างบจำกัดเริ่มที่ภาคเหนือจะคุ้มและเที่ยวได้นาน', en: 'The north (Chiang Mai, Pai, Chiang Rai) and Isan are cheapest for stays, food and transport, while the southern islands cost more due to ferries and imported goods — on a tight budget, start in the north for the best value and longer trips.' } },
    { q: { th: 'ไม่มีรถแบ็คแพ็คได้ไหม?', en: 'Can I backpack without a car?' },
      a: { th: 'ได้สบาย เชียงใหม่ ปาย และเชียงรายมีรถประจำทาง รถสองแถว และรถเช่ามอเตอร์ไซค์ราคาเบา เกาะพะงันใช้เรือและสองแถวบนเกาะ ส่วนกาญจนบุรีมีรถไฟและรถตู้จากกรุงเทพ วางแผนเป็นเมือง ๆ ต่อรถง่าย', en: 'Easily — Chiang Mai, Pai and Chiang Rai have buses, songthaews and cheap motorbike rentals, Koh Phangan uses boats and island songthaews, and Kanchanaburi has trains and minivans from Bangkok, so it is easy to hop between towns.' } },
  ],
},
{ slug: 'best-solo-travel-thailand', hero: 'bangkok', emoji: '🧳',
  th: { eyebrow: 'เที่ยวคนเดียว', h1: 'เที่ยวคนเดียว<br>ไปไหนดี-ปลอดภัย', title: 'เที่ยวคนเดียวที่ไหนดีในไทย 2026 — 5 ที่ปลอดภัย เพื่อนเยอะ | ThailandAddict',
    metaDesc: 'เที่ยวคนเดียวในไทยไปไหนดี ปลอดภัยและหาเพื่อนง่าย? รวม 5 ที่ เชียงใหม่ ปาย กรุงเทพ เกาะพะงัน เกาะเต่า พร้อมที่พัก',
    intro: 'รวมจุดหมายที่เที่ยวคนเดียวสะดวก ปลอดภัย และเจอเพื่อนนักเดินทางง่าย พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> มาครั้งแรก-เที่ยวคนเดียวเลือก <strong>เชียงใหม่</strong> (เดินทางง่าย คนเป็นมิตร) สายภูเขา-สังคมนักเดินทางเลือก <strong>ปาย</strong> สายเมืองใหญ่-ขนส่งดีเลือก <strong>กรุงเทพ</strong> สายเกาะ-เจอเพื่อนเลือก <strong>เกาะพะงัน</strong> หรือ <strong>เกาะเต่า</strong> (เรียนดำน้ำ)' },
  en: { eyebrow: 'Solo travel', h1: 'Best places for<br>solo travel', title: 'Best Places for Solo Travel in Thailand 2026 — 5 Safe, Social Picks | ThailandAddict',
    metaDesc: 'Where to travel solo in Thailand? Five safe, social picks — Chiang Mai, Pai, Bangkok, Koh Phangan and Koh Tao — with where to stay.',
    intro: 'Destinations that are easy and safe to travel solo and where it is easy to meet other travelers, each with where to stay.',
    quick: '<strong>Short answer:</strong> For a first solo trip choose <strong>Chiang Mai</strong> (easy to get around, friendly); for mountains and a traveler scene, <strong>Pai</strong>; for a big city with great transport, <strong>Bangkok</strong>; and for islands where you will meet people, <strong>Koh Phangan</strong> or <strong>Koh Tao</strong> (learn to dive).' },
  items: [
    { name: { th: 'เชียงใหม่', en: 'Chiang Mai' }, href: 'city-chiang-mai.html', stayHref: 'where-to-stay-chiang-mai.html',
      blurb: { th: 'เมืองที่เที่ยวคนเดียวง่ายและปลอดภัยสุดในไทย เดินเที่ยววัด-คาเฟ่ได้ มีคลาสทำอาหาร โฮสเทล และคอมมูนิตี้ดิจิทัลโนแมดให้เจอเพื่อน', en: 'One of the easiest and safest cities to travel solo — walkable temples and cafés, cooking classes, hostels and a digital-nomad community where it is easy to meet people.' },
      tags: { th: ['ปลอดภัย-เดินง่าย', 'เจอเพื่อนง่าย'], en: ['Safe & walkable', 'Easy to meet people'] } },
    { name: { th: 'ปาย (แม่ฮ่องสอน)', en: 'Pai (Mae Hong Son)' }, href: 'city-pai.html', stayHref: 'where-to-stay-pai.html',
      blurb: { th: 'เมืองเล็กสายชิลที่นักเดินทางคนเดียวเยอะ โฮสเทลและบาร์เป็นกันเอง ทัวร์รวมกลุ่มเที่ยวง่าย เหมาะคนอยากเจอเพื่อนใหม่ในบรรยากาศสบาย ๆ', en: 'A laid-back small town with lots of solo travelers, friendly hostels and bars, and easy group tours — great for meeting new people in a relaxed setting.' },
      tags: { th: ['สังคมนักเดินทาง', 'โฮสเทลเป็นกันเอง'], en: ['Traveler scene', 'Friendly hostels'] } },
    { name: { th: 'กรุงเทพ', en: 'Bangkok' }, href: 'city-bangkok.html', stayHref: 'where-to-stay-bangkok.html',
      blurb: { th: 'เมืองใหญ่ที่ขนส่งสาธารณะ (BTS/MRT) สะดวก ปลอดภัยในย่านหลัก มีโฮสเทล คาเฟ่ และของกินตลอดเวลา เหมาะเที่ยวคนเดียวที่อยากคล่องตัว', en: 'A big city with convenient BTS/MRT, safe in the main areas, with hostels, cafés and food around the clock — ideal for solo travelers who want to move easily.' },
      tags: { th: ['ขนส่งดี', 'โฮสเทลเยอะ'], en: ['Great transport', 'Lots of hostels'] } },
    { name: { th: 'เกาะพะงัน', en: 'Koh Phangan' }, href: 'city-koh-phangan.html', stayHref: 'where-to-stay-koh-phangan.html',
      blurb: { th: 'เกาะสายปาร์ตี้และโยคะที่เจอเพื่อนนักเดินทางง่าย ฟูลมูนปาร์ตี้ คลาสโยคะ และโฮสเทลริมหาด เหมาะเที่ยวคนเดียวที่อยากสังสรรค์', en: 'A party-and-yoga island where it is easy to meet travelers — the Full Moon Party, yoga classes and beach hostels, good for solo travelers who want to socialize.' },
      tags: { th: ['ฟูลมูน-โยคะ', 'เจอเพื่อนง่าย'], en: ['Full Moon & yoga', 'Easy to meet people'] } },
    { name: { th: 'เกาะเต่า (ผ่านชุมพร)', en: 'Koh Tao (via Chumphon)' }, href: 'city-chumphon.html', stayHref: 'where-to-stay-chumphon.html',
      blurb: { th: 'เมกกะของนักดำน้ำ คอร์สดำน้ำราคาถูกที่ทำให้เจอเพื่อนร่วมคอร์สง่าย เกาะเล็กเดินทางสะดวก ออกเรือจากชุมพร เหมาะคนเดียวที่อยากลองดำน้ำ', en: 'A diving mecca where cheap dive courses make it easy to meet coursemates — a small, easy island reached by boat from Chumphon, great for solo travelers who want to try diving.' },
      tags: { th: ['คอร์สดำน้ำ', 'เจอเพื่อนร่วมคอร์ส'], en: ['Dive courses', 'Meet coursemates'] } },
  ],
  faq: [
    { q: { th: 'เที่ยวคนเดียวในไทยปลอดภัยไหม?', en: 'Is solo travel in Thailand safe?' },
      a: { th: 'โดยรวมปลอดภัยและเป็นมิตรกับนักท่องเที่ยว โดยเฉพาะเชียงใหม่และเมืองท่องเที่ยวหลัก ควรระวังของมีค่า เลี่ยงที่เปลี่ยวยามดึก เช็กรถ/เรือให้ดี และดูแลเครื่องดื่มในปาร์ตี้ ผู้หญิงเที่ยวคนเดียวก็ทำได้ ขอแค่ใช้สามัญสำนึกปกติ', en: 'It is generally safe and traveler-friendly, especially in Chiang Mai and the main tourist towns. Mind your valuables, avoid empty areas late at night, check vehicles and boats, and watch your drinks at parties; solo women travel here fine with normal common sense.' } },
    { q: { th: 'เที่ยวคนเดียวเจอเพื่อนใหม่ที่ไหนง่ายสุด?', en: 'Where is easiest to meet other travelers?' },
      a: { th: 'ปาย เกาะพะงัน และเกาะเต่าเจอเพื่อนง่ายสุด เพราะมีโฮสเทล ทัวร์รวมกลุ่ม คลาสโยคะ และคอร์สดำน้ำ ส่วนเชียงใหม่มีคลาสทำอาหารและคอมมูนิตี้โนแมด เลือกพักโฮสเทลหรือเข้าร่วมกิจกรรมจะเจอเพื่อนเร็วขึ้น', en: 'Pai, Koh Phangan and Koh Tao are easiest, thanks to hostels, group tours, yoga classes and dive courses, while Chiang Mai has cooking classes and a nomad community — stay in hostels or join activities to meet people faster.' } },
    { q: { th: 'เที่ยวคนเดียวไม่มีรถเที่ยวได้ไหม?', en: 'Can I travel solo without a car?' },
      a: { th: 'ได้สบาย กรุงเทพมี BTS/MRT และ Grab เชียงใหม่และปายมีรถสองแถวและรถเช่ามอเตอร์ไซค์ เกาะใช้เรือและสองแถวบนเกาะ ทุกที่ในลิสต์นี้เที่ยวคนเดียวได้โดยไม่ต้องมีรถส่วนตัว', en: 'Easily — Bangkok has the BTS/MRT and Grab, Chiang Mai and Pai have songthaews and motorbike rentals, and the islands use boats and local songthaews; everywhere on this list works solo without your own car.' } },
  ],
},
{ slug: 'best-river-mekong-thailand', hero: 'nong-khai', emoji: '🛶',
  th: { eyebrow: 'ริมโขง & อีสาน', h1: 'เที่ยวริมโขง<br>ไปจังหวัดไหนดี', title: 'เที่ยวริมแม่น้ำโขงที่ไหนดีในไทย 2026 — 5 จังหวัดริมโขงวิวสวย | ThailandAddict',
    metaDesc: 'อยากเที่ยวริมแม่น้ำโขงไปจังหวัดไหนดี? รวม 5 จังหวัด หนองคาย นครพนม มุกดาหาร เลย(เชียงคาน) อุบลราชธานี พร้อมที่พัก',
    intro: 'รวมจังหวัดริมแม่น้ำโขงที่วิวสวยและบรรยากาศดี ตั้งแต่ถนนคนเดินริมโขงถึงผาชมวิว พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายเมืองริมโขง-เดินเล่นเลือก <strong>หนองคาย</strong> หรือ <strong>นครพนม</strong> (วิวฝั่งลาว) สายตลาดอินโดจีนเลือก <strong>มุกดาหาร</strong> สายเมืองเก่าบ้านไม้เลือก <strong>เชียงคาน (เลย)</strong> ส่วนสายผา-แก่ง-สองสีเลือก <strong>อุบลราชธานี</strong> (ผาแต้ม สามพันโบก)' },
  en: { eyebrow: 'Mekong & Isan', h1: 'Best Mekong<br>river towns', title: 'Best Mekong River Destinations in Thailand 2026 — 5 Scenic Picks | ThailandAddict',
    metaDesc: 'Where to travel along the Mekong in Thailand? Five scenic picks — Nong Khai, Nakhon Phanom, Mukdahan, Chiang Khan (Loei) and Ubon Ratchathani — with where to stay.',
    intro: 'Provinces along the Mekong with lovely views and atmosphere, from riverside walking streets to clifftop viewpoints, each with where to stay.',
    quick: '<strong>Short answer:</strong> For riverside towns and strolling choose <strong>Nong Khai</strong> or <strong>Nakhon Phanom</strong> (Laos views); for the Indochina market, <strong>Mukdahan</strong>; for an old wooden-house town, <strong>Chiang Khan (Loei)</strong>; and for cliffs, rapids and the two-color river, <strong>Ubon Ratchathani</strong> (Pha Taem, Sam Phan Bok).' },
  items: [
    { name: { th: 'หนองคาย', en: 'Nong Khai' }, href: 'city-nong-khai.html', stayHref: 'where-to-stay-nong-khai.html',
      blurb: { th: 'เมืองริมโขงเดินเล่นสบาย มีถนนริมโขง ตลาดท่าเสด็จ ศาลาแก้วกู่ (สวนประติมากรรม) และปรากฏการณ์บั้งไฟพญานาคช่วงออกพรรษา', en: 'An easygoing riverside town with a Mekong promenade, the Tha Sadet market, the Sala Kaew Ku sculpture park and the Naga fireball phenomenon around the end of Buddhist Lent.' },
      tags: { th: ['ริมโขง-เดินเล่น', 'ศาลาแก้วกู่'], en: ['Riverside promenade', 'Sala Kaew Ku'] } },
    { name: { th: 'นครพนม', en: 'Nakhon Phanom' }, href: 'city-nakhon-phanom.html', stayHref: 'where-to-stay-nakhon-phanom.html',
      blurb: { th: 'เมืองริมโขงวิวสวยมองเห็นภูเขาฝั่งลาว มีพระธาตุพนมศักดิ์สิทธิ์ ถนนคนเดินริมโขง และบ้านเก่าสถาปัตยกรรมฝรั่งเศส-เวียดนาม', en: 'A scenic riverside town with mountain views across to Laos, the sacred Phra That Phanom, a Mekong walking street and old French-Vietnamese architecture.' },
      tags: { th: ['วิวฝั่งลาว', 'พระธาตุพนม'], en: ['Laos views', 'Phra That Phanom'] } },
    { name: { th: 'มุกดาหาร', en: 'Mukdahan' }, href: 'city-mukdahan.html', stayHref: 'where-to-stay-mukdahan.html',
      blurb: { th: 'เมืองริมโขงชายแดนที่มีตลาดอินโดจีนขายของลาว-เวียดนาม หอแก้วมุกดาหารชมวิวเมือง และสะพานมิตรภาพไทย-ลาวข้ามไปสะหวันนะเขต', en: 'A border riverside town with the Indochina Market selling Lao and Vietnamese goods, the Ho Kaew tower with city views, and the Friendship Bridge across to Savannakhet.' },
      tags: { th: ['ตลาดอินโดจีน', 'สะพานมิตรภาพ'], en: ['Indochina Market', 'Friendship Bridge'] } },
    { name: { th: 'เชียงคาน (เลย)', en: 'Chiang Khan (Loei)' }, href: 'city-loei.html', stayHref: 'where-to-stay-chiang-khan.html',
      blurb: { th: 'เมืองริมโขงบ้านไม้เก่า ถนนคนเดินยามเย็น ตักบาตรข้าวเหนียวเช้า และทะเลหมอกที่ภูทอก เป็นเมืองริมโขงที่ฮิตสุดช่วงหน้าหนาว', en: 'A Mekong town of old wooden houses with an evening walking street, dawn sticky-rice alms and mist at Phu Thok — the most popular riverside town in the cool season.' },
      tags: { th: ['บ้านไม้เก่า', 'ตักบาตรเช้า'], en: ['Old wooden houses', 'Dawn alms'] } },
    { name: { th: 'อุบลราชธานี', en: 'Ubon Ratchathani' }, href: 'city-ubon-ratchathani.html', stayHref: 'where-to-stay-ubon-ratchathani.html',
      blurb: { th: 'อีสานใต้ริมโขง มีผาแต้ม (ภาพเขียนสีก่อนประวัติศาสตร์) สามพันโบก (แกรนด์แคนยอนน้ำโขง เห็นชัดหน้าแล้ง) และแม่น้ำสองสีที่โขงเจียม', en: 'Lower Isan on the Mekong, with Pha Taem (prehistoric cliff paintings), Sam Phan Bok (the Mekong’s “grand canyon,” best in the dry season) and the two-color river at Khong Chiam.' },
      tags: { th: ['ผาแต้ม-สามพันโบก', 'แม่น้ำสองสี'], en: ['Pha Taem & Sam Phan Bok', 'Two-color river'] } },
  ],
  faq: [
    { q: { th: 'เที่ยวริมโขงหน้าไหนดี?', en: 'What season is best along the Mekong?' },
      a: { th: 'หน้าหนาว (พ.ย.-ก.พ.) อากาศเย็น ทะเลหมอกสวย โดยเฉพาะเชียงคาน ส่วนสามพันโบกที่อุบลฯ เห็นชัดสุดหน้าแล้ง (ก.พ.-พ.ค.) เพราะน้ำลด หน้าฝนแม่น้ำเต็มและเขียวสวยแต่บางจุดน้ำท่วมแก่ง ควรเลือกช่วงตามที่อยากเห็น', en: 'The cool season (Nov–Feb) brings cool air and mist, especially in Chiang Khan, while Sam Phan Bok in Ubon shows best in the dry season (Feb–May) when the water drops; in the rains the river is full and green but some rapids submerge — pick by what you want to see.' } },
    { q: { th: 'บั้งไฟพญานาคดูที่ไหน เมื่อไหร่?', en: 'Where and when are the Naga fireballs?' },
      a: { th: 'ดูได้แถบหนองคายและพื้นที่ริมโขงใกล้เคียง ช่วงวันออกพรรษา (ราวเดือน ต.ค.) เป็นปรากฏการณ์ลูกไฟลอยขึ้นจากแม่น้ำโขงที่คนแห่ไปชมทุกปี ช่วงนั้นที่พักริมโขงเต็มเร็วมาก ควรจองล่วงหน้านาน ๆ', en: 'They are seen around Nong Khai and nearby Mekong areas at the end of Buddhist Lent (around October) — balls of light that rise from the river, drawing big crowds each year, so riverside rooms fill fast and you should book well ahead.' } },
    { q: { th: 'เที่ยวริมโขงหลายจังหวัดต่อกันได้ไหม?', en: 'Can I combine several Mekong provinces?' },
      a: { th: 'ได้ เส้นริมโขงเชื่อมต่อกันยาว เช่น เลย (เชียงคาน) - หนองคาย - นครพนม - มุกดาหาร - อุบลฯ ขับรถเลียบแม่น้ำเที่ยวต่อเนื่องได้หลายวัน เหมาะสายโรดทริปที่ชอบวิวแม่น้ำและเมืองเล็ก ๆ', en: 'Yes — the Mekong route links up over a long stretch, for example Loei (Chiang Khan) – Nong Khai – Nakhon Phanom – Mukdahan – Ubon, so you can drive along the river for several days, ideal for a road trip lover who likes river views and small towns.' } },
  ],
},
{ slug: 'best-quiet-islands-thailand', hero: 'koh-mak', emoji: '🏝️',
  th: { eyebrow: 'เกาะเงียบ & หนีคน', h1: 'เกาะเงียบ ๆ<br>หนีคนไปไหนดี', title: 'เกาะเงียบ ๆ หนีคนในไทยไปไหนดี 2026 — 5 เกาะสงบ ธรรมชาติ | ThailandAddict',
    metaDesc: 'อยากไปเกาะเงียบ ๆ หนีนักท่องเที่ยวในไทยไปไหนดี? รวม 5 เกาะสงบ เกาะกูด เกาะหมาก เกาะพยาม เกาะตรัง เกาะช้าง พร้อมที่พัก',
    intro: 'รวมเกาะที่เงียบสงบ คนไม่เยอะ ธรรมชาติสวย เหมาะหนีความวุ่นวาย พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายเกาะใหญ่เงียบ-น้ำใสเลือก <strong>เกาะกูด</strong> สายเกาะเล็กปั่นจักรยานเลือก <strong>เกาะหมาก</strong> สายเกาะโบฮีเมียนไม่มีรถเลือก <strong>เกาะพยาม (ระนอง)</strong> สายเกาะใต้น้ำใสเลือกหมู่ <strong>เกาะตรัง</strong> (กระดาน-ไหง) ส่วนเกาะใหญ่ที่ยังมีมุมเงียบเลือก <strong>เกาะช้าง</strong> (โซนใต้)' },
  en: { eyebrow: 'Quiet islands', h1: 'Quiet islands<br>away from crowds', title: 'Best Quiet Islands in Thailand 2026 — 5 Peaceful Escapes | ThailandAddict',
    metaDesc: 'Which Thai islands are quiet and away from the crowds? Five peaceful picks — Koh Kood, Koh Mak, Koh Phayam, the Trang Islands and Koh Chang — with where to stay.',
    intro: 'Islands that stay quiet, with few crowds and lovely nature, ideal for escaping the bustle, each with where to stay.',
    quick: '<strong>Short answer:</strong> For a big, quiet, clear-water island choose <strong>Koh Kood</strong>; for a small, cycle-friendly one, <strong>Koh Mak</strong>; for a car-free bohemian island, <strong>Koh Phayam (Ranong)</strong>; for clear-water southern islands, the <strong>Trang Islands</strong> (Kradan/Ngai); and for a bigger island that still has quiet corners, <strong>Koh Chang</strong> (the south).' },
  items: [
    { name: { th: 'เกาะกูด (ตราด)', en: 'Koh Kood (Trat)' }, href: 'city-koh-kood.html', stayHref: 'where-to-stay-koh-kood.html',
      blurb: { th: 'เกาะใหญ่ฝั่งตะวันออก น้ำใสนิ่ง ป่าเขียว น้ำตก หาดเงียบ ไม่มีไนต์ไลฟ์ เหมาะพักผ่อนเงียบ ๆ และฮันนีมูน', en: 'A large east-coast island with calm clear water, green jungle, waterfalls and quiet beaches and no nightlife — ideal for a peaceful rest and honeymoons.' },
      tags: { th: ['น้ำใส-เงียบ', 'ไม่มีไนต์ไลฟ์'], en: ['Clear & quiet', 'No nightlife'] } },
    { name: { th: 'เกาะหมาก (ตราด)', en: 'Koh Mak (Trat)' }, href: 'city-koh-mak.html', stayHref: 'where-to-stay-koh-mak.html',
      blurb: { th: 'เกาะเล็กแบนปั่นจักรยานเที่ยวได้ น้ำนิ่งใส หาดเงียบ เจ้าของรีสอร์ตเป็นกันเอง เหมาะคู่รักและคนอยากชิลแบบช้า ๆ', en: 'A small, flat island you can cycle around, with calm clear water, quiet beaches and friendly resort owners — great for couples and a slow, mellow stay.' },
      tags: { th: ['ปั่นจักรยาน', 'น้ำนิ่ง'], en: ['Cycling', 'Calm water'] } },
    { name: { th: 'เกาะพยาม (ระนอง)', en: 'Koh Phayam (Ranong)' }, href: 'city-ranong.html', stayHref: 'where-to-stay-ranong.html',
      blurb: { th: 'เกาะฝั่งอันดามันเหนือ บรรยากาศโบฮีเมียน ไม่มีรถยนต์ (ใช้มอเตอร์ไซค์) หาดเงียบ พระอาทิตย์ตกสวย เหมาะคนอยากหนีคนจริง ๆ', en: 'A northern Andaman island with a bohemian feel and no cars (only motorbikes), quiet beaches and fine sunsets — for travelers who really want to get away.' },
      tags: { th: ['ไม่มีรถยนต์', 'โบฮีเมียน'], en: ['Car-free', 'Bohemian'] } },
    { name: { th: 'หมู่เกาะตรัง (กระดาน-ไหง)', en: 'Trang Islands (Kradan/Ngai)' }, href: 'city-trang.html', stayHref: 'where-to-stay-trang.html',
      blurb: { th: 'หาดทรายขาว น้ำใส ดำน้ำตื้นสวย และมีถ้ำมรกตที่ต้องว่ายลอดเข้าไป เงียบกว่าเกาะดัง ๆ ในอันดามัน เหมาะสายทะเลใสที่ไม่ชอบคนเยอะ', en: 'White sand, clear water and lovely snorkeling, plus the Emerald Cave you swim into — quieter than the famous Andaman islands, great for clear-sea lovers who avoid crowds.' },
      tags: { th: ['น้ำใส-เงียบ', 'ถ้ำมรกต'], en: ['Clear & quiet', 'Emerald Cave'] } },
    { name: { th: 'เกาะช้าง (ตราด)', en: 'Koh Chang (Trat)' }, href: 'city-koh-chang.html', stayHref: 'where-to-stay-koh-chang.html',
      blurb: { th: 'เกาะใหญ่ป่าเขียวและน้ำตก ฝั่งตะวันตกมีหาดคึกคัก แต่โซนใต้อย่างบางเบ้า-คลองกลอยและฝั่งตะวันออกยังเงียบสงบ เหมาะคนอยากได้เกาะใหญ่ที่ยังมีมุมสงบ', en: 'A big, jungly island with waterfalls; the west coast is livelier, but the south around Bang Bao and Klong Kloi and the east coast stay quiet — good for those who want a big island with calm corners.' },
      tags: { th: ['ป่า-น้ำตก', 'โซนใต้เงียบ'], en: ['Jungle & falls', 'Quiet south'] } },
  ],
  faq: [
    { q: { th: 'เกาะไหนเงียบสุดในไทย?', en: 'Which Thai island is quietest?' },
      a: { th: 'เกาะกูดและเกาะหมาก (ตราด) กับเกาะพยาม (ระนอง) ขึ้นชื่อว่าเงียบและเป็นส่วนตัวที่สุด ไม่มีไนต์ไลฟ์หรือคนเยอะ น้ำใสและธรรมชาติสมบูรณ์ เหมาะคนอยากพักผ่อนจริง ๆ หนีความวุ่นวายของเกาะดัง', en: 'Koh Kood and Koh Mak (Trat) and Koh Phayam (Ranong) are known as the quietest and most private, with no nightlife or crowds, clear water and rich nature — perfect for a real rest away from the busy islands.' } },
    { q: { th: 'เกาะเงียบไปหน้าไหนดี?', en: 'What season for the quiet islands?' },
      a: { th: 'เกาะฝั่งตะวันออก (กูด หมาก ช้าง) และอันดามัน (พยาม ตรัง) สวยสุดหน้าแล้ง-ไฮซีซั่น (พ.ย.-เม.ย.) น้ำใสและทะเลสงบ ส่วนหน้าฝนคลื่นแรงและบางรีสอร์ต/เรือหยุดให้บริการ ควรเช็กตารางเรือและที่พักก่อนไป', en: 'The eastern islands (Kood, Mak, Chang) and the Andaman (Phayam, Trang) are best in the dry high season (Nov–Apr) with clear water and calm seas, while in the rains the waves pick up and some resorts and boats pause — check ferry schedules and stays before you go.' } },
    { q: { th: 'เกาะเงียบเดินทางยากไหม?', en: 'Are the quiet islands hard to reach?' },
      a: { th: 'ต้องต่อเรือและวางแผนสักหน่อย เกาะกูด-หมากออกเรือจากตราด เกาะพยามจากระนอง หมู่เกาะตรังจากท่าเรือในตรัง ส่วนเกาะช้างใกล้สุดเพราะเรือเฟอร์รีรถขึ้นได้ ความเงียบแลกกับการเดินทางที่นานขึ้นนิดหน่อย แต่คุ้ม', en: 'They take a ferry and some planning — Koh Kood and Koh Mak leave from Trat, Koh Phayam from Ranong and the Trang Islands from Trang’s piers, while Koh Chang is the easiest with a car ferry; the quiet is worth the slightly longer trip.' } },
  ],
},
{ slug: 'best-historic-old-towns-thailand', hero: 'sukhothai', emoji: '🏛️',
  th: { eyebrow: 'เมืองเก่า & ประวัติศาสตร์', h1: 'เมืองเก่า<br>ไปเที่ยวไหนดี', title: 'เที่ยวเมืองเก่าที่ไหนดีในไทย 2026 — 6 เมืองเก่าเสน่ห์ ประวัติศาสตร์ | ThailandAddict',
    metaDesc: 'อยากเที่ยวเมืองเก่า ย่านเก่า ในไทยไปไหนดี? รวม 6 เมือง อยุธยา สุโขทัย ลำปาง ภูเก็ต(เมืองเก่า) สงขลา จันทบุรี พร้อมที่พัก',
    intro: 'รวมเมืองเก่าและย่านเก่าที่มีเสน่ห์ ตั้งแต่ราชธานีโบราณถึงย่านตึกชิโน-โปรตุกีส พร้อมลิงก์ที่พัก',
    quick: '<strong>คำตอบสั้น ๆ:</strong> สายราชธานีโบราณเลือก <strong>อยุธยา</strong> และ <strong>สุโขทัย</strong> สายเมืองเหนือบ้านไม้-รถม้าเลือก <strong>ลำปาง</strong> สายย่านชิโน-โปรตุกีสเลือก <strong>ภูเก็ต (เมืองเก่า)</strong> หรือ <strong>สงขลา</strong> ส่วนสายชุมชนริมน้ำเก่าเลือก <strong>จันทบุรี</strong>' },
  en: { eyebrow: 'Old towns & history', h1: 'Best historic<br>old towns', title: 'Best Historic Old Towns in Thailand 2026 — 6 Charming Picks | ThailandAddict',
    metaDesc: 'Where to see historic old towns in Thailand? Six picks — Ayutthaya, Sukhothai, Lampang, Phuket Old Town, Songkhla and Chanthaburi — with where to stay.',
    intro: 'Charming old towns and historic quarters, from ancient capitals to Sino-Portuguese shophouse streets, each with where to stay.',
    quick: '<strong>Short answer:</strong> For ancient capitals choose <strong>Ayutthaya</strong> and <strong>Sukhothai</strong>; for a northern wooden-house, horse-carriage town, <strong>Lampang</strong>; for Sino-Portuguese quarters, <strong>Phuket Old Town</strong> or <strong>Songkhla</strong>; and for an old riverside community, <strong>Chanthaburi</strong>.' },
  items: [
    { name: { th: 'อยุธยา', en: 'Ayutthaya' }, href: 'city-ayutthaya.html', stayHref: 'where-to-stay-ayutthaya.html',
      blurb: { th: 'อดีตราชธานีและเมืองมรดกโลก โบราณสถาน วัด และเจดีย์ทั่วเกาะเมือง ปั่นจักรยานหรือนั่งเรือรอบเกาะชมประวัติศาสตร์ได้ในวันเดียว', en: 'A former capital and World Heritage city, with ruins, temples and stupas across the island — cycle or take a boat around to soak up the history in a day.' },
      tags: { th: ['มรดกโลก', 'โบราณสถาน'], en: ['World Heritage', 'Ancient ruins'] } },
    { name: { th: 'สุโขทัย', en: 'Sukhothai' }, href: 'city-sukhothai.html', stayHref: 'where-to-stay-sukhothai.html',
      blurb: { th: 'ราชธานีแรกของไทย อุทยานประวัติศาสตร์กว้างขวางจัดสวนสวยงาม วัดมหาธาตุและพระพุทธรูปสมัยสุโขทัยงดงาม เหมาะปั่นจักรยานชมเงียบ ๆ', en: 'Thailand’s first capital, with a spacious, beautifully landscaped historical park, Wat Mahathat and graceful Sukhothai-era Buddha images — lovely to explore quietly by bike.' },
      tags: { th: ['อุทยานประวัติศาสตร์', 'ปั่นจักรยาน'], en: ['Historical park', 'Cycling'] } },
    { name: { th: 'ลำปาง', en: 'Lampang' }, href: 'city-lampang.html', stayHref: 'where-to-stay-lampang.html',
      blurb: { th: 'เมืองเหนือเนิบ ๆ มีรถม้าเป็นเอกลักษณ์ ย่านเก่าตลาดกาดกองต้าบ้านไม้ริมน้ำวัง และวัดไม้สวย ๆ เหมาะสายเมืองเก่าที่ชอบบรรยากาศช้า ๆ', en: 'A slow-paced northern town known for its horse carriages, the Kad Kong Ta old street of wooden riverside houses and beautiful wooden temples — great for old-town lovers who like an unhurried pace.' },
      tags: { th: ['รถม้า', 'กาดกองต้า'], en: ['Horse carriages', 'Kad Kong Ta'] } },
    { name: { th: 'ภูเก็ต (เมืองเก่า)', en: 'Phuket Old Town' }, href: 'city-phuket.html', stayHref: 'where-to-stay-phuket.html',
      blurb: { th: 'ย่านเมืองเก่าตึกชิโน-โปรตุกีสสีสันสดใส คาเฟ่ ร้านอาหารเปอรานากัน และสตรีทอาร์ต เดินเที่ยวถ่ายรูปได้เพลิน ต่างจากภาพภูเก็ตสายหาด', en: 'A colorful Sino-Portuguese old quarter with cafés, Peranakan restaurants and street art — a delight to walk and photograph, a different side of beach-famous Phuket.' },
      tags: { th: ['ชิโน-โปรตุกีส', 'สตรีทอาร์ต'], en: ['Sino-Portuguese', 'Street art'] } },
    { name: { th: 'สงขลา', en: 'Songkhla' }, href: 'city-songkhla.html', stayHref: 'where-to-stay-songkhla.html',
      blurb: { th: 'เมืองเก่าสงขลาย่านถนนนางงาม-นครนอกตึกชิโน-โปรตุกีส คาเฟ่ สตรีทอาร์ต และของกินพื้นถิ่น ใกล้หาดสมิหลาและหับ โห้ หิ้น เหมาะสายเมืองเก่าภาคใต้', en: 'Songkhla’s old town around Nang Ngam and Nakhon Nok streets has Sino-Portuguese buildings, cafés, street art and local food, near Samila Beach and the Hub Ho Hin mill — great southern old-town wandering.' },
      tags: { th: ['เมืองเก่าใต้', 'สตรีทอาร์ต'], en: ['Southern old town', 'Street art'] } },
    { name: { th: 'จันทบุรี', en: 'Chanthaburi' }, href: 'city-chanthaburi.html', stayHref: 'where-to-stay-chanthaburi.html',
      blurb: { th: 'ชุมชนริมน้ำจันทบูรบ้านไม้เก่าและอาสนวิหารคาทอลิกที่ใหญ่ที่สุดในไทย ย่านค้าพลอยเก่าแก่ และของกินพื้นถิ่น เหมาะสายเมืองเก่าภาคตะวันออกแบบเงียบ ๆ', en: 'The Chanthaboon riverside community of old wooden houses and Thailand’s largest Catholic cathedral, with a historic gem-trading quarter and local food — a quiet east-coast old town.' },
      tags: { th: ['ชุมชนริมน้ำ', 'อาสนวิหาร'], en: ['Riverside community', 'Cathedral'] } },
  ],
  faq: [
    { q: { th: 'เที่ยวเมืองเก่าเลือกอยุธยาหรือสุโขทัย?', en: 'Ayutthaya or Sukhothai for old towns?' },
      a: { th: 'อยุธยาใกล้กรุงเทพและโบราณสถานใหญ่ เหมาะไปเช้า-เย็นกลับ ส่วนสุโขทัยไกลกว่าแต่อุทยานเป็นระเบียบและเงียบสงบ ปั่นจักรยานสบาย ถ้ามีเวลาไปทั้งสองที่ได้จะเห็นพัฒนาการศิลปะไทยตั้งแต่สุโขทัยถึงอยุธยา', en: 'Ayutthaya is near Bangkok with large ruins and is good as a day trip, while Sukhothai is farther but tidier and calmer and easy to cycle; with time, visiting both shows the development of Thai art from Sukhothai to Ayutthaya.' } },
    { q: { th: 'เที่ยวย่านชิโน-โปรตุกีสไปไหนดี?', en: 'Where for Sino-Portuguese quarters?' },
      a: { th: 'ภูเก็ตเมืองเก่าและสงขลาเป็นสองย่านชิโน-โปรตุกีสที่สวยและมีชีวิตชีวาที่สุด มีตึกสีสันสดใส คาเฟ่ สตรีทอาร์ต และอาหารเปอรานากัน เดินถ่ายรูปได้เพลิน ทั้งคู่อยู่ใกล้ทะเลเที่ยวควบหาดได้', en: 'Phuket Old Town and Songkhla are the two prettiest, liveliest Sino-Portuguese quarters, with colorful buildings, cafés, street art and Peranakan food that are a joy to walk and photograph, and both are near the coast to combine with a beach.' } },
    { q: { th: 'เที่ยวเมืองเก่าควบที่เที่ยวอื่นได้ไหม?', en: 'Can I combine old towns with other sights?' },
      a: { th: 'ได้ ภูเก็ตเมืองเก่าควบหาดและทัวร์เกาะ สงขลาควบหาดสมิหลาและหาดใหญ่ จันทบุรีควบน้ำตกพลิ้วและทะเลตราด ส่วนลำปางอยู่ระหว่างทางเชียงใหม่-กรุงเทพ แวะเที่ยวเมืองเก่าได้ลงตัว', en: 'Yes — Phuket Old Town pairs with the beaches and island tours, Songkhla with Samila Beach and Hat Yai, Chanthaburi with Phlio waterfall and the Trat coast, and Lampang sits on the Chiang Mai–Bangkok route for an easy old-town stop.' } },
  ],
},
];

// ---------- builder ----------
function buildArticle(L, loc) {
  const en = loc === 'en';
  const t = en ? L.en : L.th;
  const stayLabel = en ? '🏨 Where to stay' : '🏨 พักย่านไหน';
  const ranked = {
    kind: 'ranked',
    items: L.items.map((it, i) => ({
      rank: i + 1, name: it.name[loc], href: it.href, blurb: it.blurb[loc],
      ...(it.stayHref ? { meta: `<a href="${it.stayHref}">${stayLabel}</a>` } : {}),
      tags: (it.tags && it.tags[loc]) || [],
    })),
  };
  const blocks = [
    { kind: 'p', html: t.quick },
    { kind: 'h2', text: en ? 'The picks, ranked' : 'จัดอันดับให้เลือก', id: 'picks' },
    ranked,
    { kind: 'cta', text: en ? 'Not sure yet? Compare destinations and build your trip in the Plan hub.' : 'ยังเลือกไม่ได้? เทียบจุดหมายและวางแผนต่อในศูนย์รวมคู่มือเที่ยว', href: 'plan-your-trip.html', label: en ? '🧭 Plan your trip' : '🧭 วางแผนเที่ยว' },
  ];
  // related: each item's city/area + plan hub + destinations
  const seen = new Set();
  const rel = [];
  for (const it of L.items) { if (!seen.has(it.href)) { seen.add(it.href); rel.push({ href: it.href, title: it.name[loc] }); } }
  rel.push({ href: 'tourist-cities.html', title: en ? '🗺️ All top destinations' : '🗺️ เมืองท่องเที่ยวทั้งหมด' });
  rel.push({ href: 'plan-your-trip.html', title: en ? '🧭 Plan Your Trip hub' : '🧭 ศูนย์รวมคู่มือเตรียมตัว' });
  return {
    slug: L.slug, type: 'guide', cluster: 'thailand',
    title: t.title, metaDesc: t.metaDesc, ogTitle: t.title.split(' | ')[0], ogDesc: t.intro,
    image: `/images/heroes/${L.hero}.jpg`, heroImg: `/images/heroes/${L.hero}.jpg`,
    crumbCity: en ? 'Top destinations' : 'เมืองท่องเที่ยว', crumbCityHref: 'tourist-cities.html',
    regionLabel: '🇹🇭 Thailand', regionHref: 'country-thailand.html',
    eyebrow: t.eyebrow, h1: t.h1, heroEmoji: L.emoji, intro: t.intro,
    chips: en ? ['Ranked', 'Real destinations', 'Where to stay'] : ['จัดอันดับ', 'ที่จริงทั้งหมด', 'พร้อมที่พัก'],
    readTime: en ? '5 min read' : '5 นาที',
    publishedDate: DATE, modifiedDate: DATE, blocks,
    faq: L.faq.map((f) => ({ q: f.q[loc], a: f.a[loc] })),
    related: rel.slice(0, 8),
  };
}

// ---------- write ----------
let n = 0; const leaks = [], misaligned = [];
// validate all link targets exist (city/where-to-stay slug or a hub) before writing
const slugSet = new Set(fs.readdirSync(A_TH).filter((f) => f.endsWith('.json')).map((f) => f.slice(0, -5)));
const hubSet = new Set(fs.readdirSync(PUB).filter((f) => f.endsWith('.html')).map((f) => f.slice(0, -5)));
const valid = (href) => { const b = href.replace(/\.html$/, ''); return slugSet.has(b) || hubSet.has(b); };
const badLinks = [];
for (const L of LISTS) for (const it of L.items) { for (const h of [it.href, it.stayHref].filter(Boolean)) if (!valid(h)) badLinks.push(`${L.slug}:${h}`); }
if (badLinks.length) { console.error('ABORT — broken target links:', badLinks); process.exit(1); }

for (const L of LISTS) {
  const th = buildArticle(L, 'th'), en = buildArticle(L, 'en');
  if (th.blocks.map((b) => b.kind).join() !== en.blocks.map((b) => b.kind).join()) { misaligned.push(L.slug); continue; }
  if (Object.keys(th).sort().join() !== Object.keys(en).sort().join()) { misaligned.push(L.slug + ':keys'); continue; }
  if (hasThai(JSON.stringify(en))) { leaks.push(L.slug); continue; }
  fs.writeFileSync(path.join(A_TH, L.slug + '.json'), JSON.stringify(th, null, 2) + '\n');
  fs.writeFileSync(path.join(A_EN, L.slug + '.json'), JSON.stringify(en, null, 2) + '\n');
  n++;
}
console.log(JSON.stringify({ written: n, slugs: LISTS.map((l) => l.slug), enThaiLeaks: leaks, misaligned }, null, 2));
