import { getCollection } from 'astro:content';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Pages that exist ONLY at the site root — no /en/ twin, no localized twin. Verified against a full build:
// dist has 7,435 root pages vs 7,432 under /en/, and exactly these 3 are the difference. link() must never
// locale-prefix them or /trip becomes /en/trip → 404. Keep in sync if a root-only page is added.
export const ROOT_ONLY_SLUGS = new Set(['trip', 'my-list', 'font-compare']);

// The set of slugs that actually have a page under /<loc>/ — localized content
// (reviews/roundups/articles-<loc>) PLUS the static hub pages in public/<loc>/
// (city/area/region/activities, generated by localize.mjs + gen-hubs before the astro build).
// A layout's link() consults this so a cross-link on a localized page points at the in-locale
// page when it exists, and falls back to /en/ (which always exists) instead of a 404 /<loc>/<slug>.
// Memoized per locale — built once, reused across every page of that locale.
const _localizedSlugCache: Record<string, Set<string>> = {};
export async function localizedSlugSet(loc: string): Promise<Set<string>> {
  if (_localizedSlugCache[loc]) return _localizedSlugCache[loc];
  const s = new Set<string>();
  const cap = loc.charAt(0).toUpperCase() + loc.slice(1);   // zh -> Zh
  for (const kind of ['reviews', 'roundups', 'articles']) {
    try {
      for (const e of (await getCollection((kind + cap) as any)) as any[]) s.add(e.data.slug);
    } catch { /* collection may not exist for this locale */ }
  }
  try {
    const pubDir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../public', loc);
    for (const f of fs.readdirSync(pubDir)) if (f.endsWith('.html')) s.add(f.replace(/\.html$/, ''));
  } catch { /* no public/<loc> dir */ }
  _localizedSlugCache[loc] = s;
  return s;
}

// Generic version: build a map slug -> extra locales (beyond th/en) that have a translated twin,
// given the 7 new-locale collection names for a content type (articles/reviews/roundups).
async function extraLocalesFor(cols: Array<[string, string]>): Promise<Record<string, string[]>> {
  const m: Record<string, string[]> = {};
  for (const [loc, col] of cols) {
    let entries: Array<{ data: { slug: string } }> = [];
    try {
      entries = (await getCollection(col as any)) as any;
    } catch {
      entries = [];
    }
    for (const e of entries) {
      (m[e.data.slug] ||= []).push(loc);
    }
  }
  return m;
}

// Build a map: article slug -> array of extra locales (beyond th/en) that have a translated twin.
// Used by the routes to tell ArticleLayout which language-switcher options a page should show,
// so a page only offers locales that actually exist (no dead switcher links).
export async function extraLocalesBySlug(): Promise<Record<string, string[]>> {
  return extraLocalesFor([
    ['zh', 'articlesZh'], ['ru', 'articlesRu'], ['ko', 'articlesKo'],
    ['ja', 'articlesJa'], ['hi', 'articlesHi'], ['he', 'articlesHe'], ['ar', 'articlesAr'],
  ]);
}

// Same idea for the 30 tourism-city hotel roundups + their linked individual reviews
// (booking-funnel i18n — not translated site-wide, only for these curated slugs).
export async function extraReviewLocalesBySlug(): Promise<Record<string, string[]>> {
  return extraLocalesFor([
    ['zh', 'reviewsZh'], ['ru', 'reviewsRu'], ['ko', 'reviewsKo'],
    ['ja', 'reviewsJa'], ['hi', 'reviewsHi'], ['he', 'reviewsHe'], ['ar', 'reviewsAr'],
  ]);
}
export async function extraRoundupLocalesBySlug(): Promise<Record<string, string[]>> {
  return extraLocalesFor([
    ['zh', 'roundupsZh'], ['ru', 'roundupsRu'], ['ko', 'roundupsKo'],
    ['ja', 'roundupsJa'], ['hi', 'roundupsHi'], ['he', 'roundupsHe'], ['ar', 'roundupsAr'],
  ]);
}
